<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PreChangeInCashout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>30d813ce-9f11-4c36-8fd2-33f267b8953c</testSuiteGuid>
   <testCaseLink>
      <guid>eae51a27-75b1-4784-a487-1553ab5e6da1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7707ab53-d9f5-4124-863a-53ebb1731ec2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e882d49f-8449-498f-ab6e-b3dd659c6dd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f124f883-295b-417a-b201-157bcf482765</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f124f883-295b-417a-b201-157bcf482765</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>5c4e6695-bd7b-4104-bbd8-0abc85af35d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f124f883-295b-417a-b201-157bcf482765</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>b52673a0-3913-4514-83d0-f6aff6c54b36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>235fdd5a-0134-42f1-8777-4079963d847a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/CustomerDetailForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5fddfdc2-6915-492d-aade-7a1c2e73d41b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PaperbaseAmendmentWithAPI/PreReleaseChanges/LoanInformationForPreReleaseCashoutChange</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70af5618-fe86-4e72-a6e0-6fa586ec4f64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eb35422-426c-4b42-ab24-9356dbc08329</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46b0c3d9-b803-4838-9223-6adef4702fdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f337240-f9c0-47c1-b9b4-46cbdc9692fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bb542b7-52e0-44ee-9c47-02646676728d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>906a9c15-fd35-4ae6-ae37-071b040db091</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3197b9d1-6697-4946-8cf6-c165e48f12c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>815be9a0-af7b-43fa-9452-eb1482dd9856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99c00cb-2f66-4241-98e2-e0370957c2c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6e3a09-dd6c-4898-a3e7-e63e5558bae7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec1823c-429f-40f0-94a0-08db41b9902b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3bfac2a-ea67-4d35-88bb-10476ba5f8ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/DocumentChecklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>52d1b454-590b-464e-a392-30daa8b936a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/CollateralInfo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>64bd8725-bda8-48ae-a39a-a1de91970a07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
