<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testSuiteWithoutAPIChangeInDOB</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>24c69419-e7f6-4aa3-909a-ae8652ab5a79</testSuiteGuid>
   <testCaseLink>
      <guid>cad321f7-d7b5-4545-8df5-41bcf2add214</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a502c933-ccf0-4ad5-884a-b7d8f6141b5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/HomePage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>553a1cfa-87ce-4a5e-8ad2-ec47093417c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/SelectAutoLoan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>99c38fb1-f7b9-48ea-923a-61ad1680f638</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/LetsgetStarted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7e6e8a9e-ce9c-4c6e-992f-6dd20f1da226</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/LoanDetails</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInfoForWithoutAPI</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>brand</value>
         <variableId>44449700-05e4-492e-a001-486504efb459</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>unitDescription</value>
         <variableId>7c3c9499-ecc5-49d5-93f2-1e4a7e21bf2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanTerm</value>
         <variableId>4d50f680-964d-4bbb-b746-10d1955b4329</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>downpaymentValue</value>
         <variableId>ff1b30c3-5ce5-4481-9ae2-69619d3067e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualCashOut</value>
         <variableId>48b870c9-7f4e-4416-bcd7-0d72dfbdbcc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf18965c-7b62-4c92-b57a-d651b4b9d8f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>insuranceType</value>
         <variableId>ae98f721-171d-41e5-93f1-467530a79a4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b74f8aa5-b745-481d-9f0b-53916bd9b669</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/BorrowerDetail</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6a53ade3-edbe-4440-91d4-faf8af67852c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/BorrowerDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fst_Name</value>
         <variableId>411c40a8-4314-4c65-9ee6-49c35a43d4bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mid_Name</value>
         <variableId>bdd0aa3f-205a-4889-8bec-3cf198f538d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lst_Name</value>
         <variableId>f2c962c8-f594-4c98-9f5f-1517f180cd67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffix</value>
         <variableId>d9a32008-833f-432d-b1c3-f2e381dd8942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>maritalStatus</value>
         <variableId>7821773d-69d6-4a6a-b102-9fd8806ec712</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>7842892e-d078-4baf-938f-84bb227714df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>36c0c017-2309-45dc-a2fe-2d2c868eddb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mob_Num</value>
         <variableId>90c5640a-5dd9-4924-a1a9-4ac1549b3a00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6a53ade3-edbe-4440-91d4-faf8af67852c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>residence</value>
         <variableId>2618a65d-1cbd-4e11-ba71-563cb3b2e1e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c82b4767-69f8-4baa-8a2a-4c01684460f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/ConfirmationPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f41a0301-63e9-4a78-97ca-60f9d00c2c3f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/InitalCheckingWithoutAPIPrequalified</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ff792fc4-36ae-4059-a1bd-7283ee181c6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/AdditionalPageWithoutAPI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f4741a58-a88f-471a-ad22-1d0955ad5a62</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AdditionalDataForWithoutAPI</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f4741a58-a88f-471a-ad22-1d0955ad5a62</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerRelationshipWithBorrower</value>
         <variableId>44744621-1260-4a15-ac77-e0d02108fd71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f4741a58-a88f-471a-ad22-1d0955ad5a62</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerFirstName</value>
         <variableId>32f9cff8-183b-4347-a29e-96f1d3c083f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f4741a58-a88f-471a-ad22-1d0955ad5a62</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerMiddleName</value>
         <variableId>77cc8756-6169-4097-a9c9-99be7613b904</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f4741a58-a88f-471a-ad22-1d0955ad5a62</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerLastName</value>
         <variableId>71b0b573-22bc-4009-9acc-f9724c9845a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f4741a58-a88f-471a-ad22-1d0955ad5a62</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerSuffix</value>
         <variableId>f3931e82-ffc4-48f0-ba97-6624284c4b7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38b89a15-1d77-435e-9724-60490ed6a0a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/DocumentUploadPageWithout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>77f146b5-e110-4000-8f8b-3ba75807ceb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/submitpagesuccessForWithoutAPI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>31af34cf-55ed-4c16-aa93-3060c48ee730</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>157c5ae4-c378-48d8-acab-506499ada93d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>157c5ae4-c378-48d8-acab-506499ada93d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>157c5ae4-c378-48d8-acab-506499ada93d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebcb2875-95b1-4a87-89ca-4a52fdeda2d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/PreReleaseChanges/ClientInformationDOBChange</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0e2bb8e3-9833-4000-9865-d260ce9d7c68</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/LoanInformationForPreRelease</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6018ae3d-753c-4e40-80f8-2c953a054cbb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInformationForPreRelease</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marketingPromoCode</value>
         <variableId>7ea9113b-a4e2-42f2-b010-ebaa86476942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanPurpose</value>
         <variableId>cccd40d3-844c-40c6-8c57-3c327eeb4c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfRelease</value>
         <variableId>1d64916c-27ae-4c7d-b471-b872dff09c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>scheduleUnitReleaseDate</value>
         <variableId>13281907-eb91-455b-b210-4bf877477894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualUnitReleaseDate</value>
         <variableId>68264b98-57f2-46d8-97d6-78f6abd52cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentType</value>
         <variableId>55981167-f0a6-4029-8833-e3c62d756e1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentFrequecy</value>
         <variableId>f3cc6c4f-53b1-4f4a-8eb8-99d9d61585e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfPayment</value>
         <variableId>8092ce41-2be0-405f-9b27-b75e0bd0ea49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>effectiveDateOfAda</value>
         <variableId>f401b8a3-5544-4c6b-8e3d-728ab654dbd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountNumber</value>
         <variableId>df09e952-ec66-420e-ada0-3099d6546b1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6018ae3d-753c-4e40-80f8-2c953a054cbb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountName</value>
         <variableId>d788b0b4-e6d1-4e17-90b8-b48c4b4bd8f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91d1ae93-56c7-41dd-9e88-e215a90dc1bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DocumentCheckListForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2d5d0c60-444c-46c6-80aa-de85600a1c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/CollateralInformationForPreRelease</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d3f1819-ed7e-4d94-981b-5bead5dc434d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CollateralInfoForPreRelease</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d3f1819-ed7e-4d94-981b-5bead5dc434d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>serialOrChessisNum</value>
         <variableId>0d7f3c48-f7dc-436d-a3a2-3d6c54bba095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d3f1819-ed7e-4d94-981b-5bead5dc434d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>motorOrEngineNum</value>
         <variableId>6c924381-06e9-4798-b837-ebbc854b0094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d3f1819-ed7e-4d94-981b-5bead5dc434d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>conductionSticker</value>
         <variableId>715eca79-7ae2-4cdd-b1f9-74739f12e1f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9845427-7df5-41a9-a12b-7d1899a8e207</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c5ddb9c2-c5ef-473c-a9d9-372ff139578c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>08885e31-76a9-4a78-b4e2-4ad3baa9aa26</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Rework</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>08885e31-76a9-4a78-b4e2-4ad3baa9aa26</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>08885e31-76a9-4a78-b4e2-4ad3baa9aa26</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2a5b13e-4d8d-4903-b48d-72c8d10773bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/ReworkPortal/ConfirmationPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>971b62d3-bc89-45c5-9133-305b88ff000d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/ReworkPortal/InitalCheckingWithoutAPIPrequalified</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c43abb3e-7467-4e0d-a14e-2fd45cf03da0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/ReworkPortal/AdditionalPageWithoutAPI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18ec7eff-5a82-4805-853e-2c8e1e7adedb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6f8a348-af18-48cf-aff1-2a3f4526c95d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636ebc7c-039a-4b4e-b92b-5aa78e663358</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e2f8c35-9e28-4fec-a457-5757ce365bc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6edec0a-7e0a-4086-befc-8c644a686f71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40ba0cd6-a24b-4953-bb63-76d29233da8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/ReworkPortal/DocumentUploadPageWith</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>11a73327-bdfd-4e89-8ecb-3ed356e96445</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7fd738fc-3cf5-4c47-8eb4-0e78c1c768e4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7fd738fc-3cf5-4c47-8eb4-0e78c1c768e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>66be9155-8696-4a98-9c7e-39d0aec15729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7fd738fc-3cf5-4c47-8eb4-0e78c1c768e4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>483dc7de-05e4-4747-8b3c-82bd417f2066</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fa00c98-250a-4f04-b381-4dfb432a649c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/ClientInfo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8c53b045-7b5b-4f5f-bbaf-2e2a8d273606</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/LoanInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1ef6b9fc-5fb6-40a4-b832-3f63179015fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/CollateralInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f78cef05-8f91-4cbc-907f-159da72d2026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/DisbursementInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>05730248-196a-4c08-9d2e-3658d9063c69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AmendmentWithoutAPI/AfterReworkPreRelease/Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b102d320-887e-47a9-9c60-56fdfa000674</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b4b9e5eb-4aa5-4b65-b4ad-f38e76f8d57a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPostData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b4b9e5eb-4aa5-4b65-b4ad-f38e76f8d57a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b4b9e5eb-4aa5-4b65-b4ad-f38e76f8d57a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8d3323d-f145-4d35-b610-6a404424fe6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/PostReleaseSubmit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
