<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testSuiteNSTPPreAndPost</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a6ad6910-0155-4c50-816d-0bcccde94fb1</testSuiteGuid>
   <testCaseLink>
      <guid>f8042499-0dc4-4ac4-8ba4-4136b473277d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2425ed3a-03d7-4e40-b981-591d9d590d7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForManageLoanPreAndPost/homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f71b59ec-738d-482b-9244-ad7077dc887f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a88d8796-03ab-41a7-8fca-dabdecb989a6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a88d8796-03ab-41a7-8fca-dabdecb989a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a88d8796-03ab-41a7-8fca-dabdecb989a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6aca23b-229e-446c-8ddc-8bcdcdf7302e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/CustomerDetailForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e5f675e0-e0c4-4ffa-ad23-86e4814195fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/LoanInformationForPreRelease</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>983f3906-d8cb-4bca-82dc-aa744cc32181</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInformationForPreRelease</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marketingPromoCode</value>
         <variableId>7ea9113b-a4e2-42f2-b010-ebaa86476942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanPurpose</value>
         <variableId>cccd40d3-844c-40c6-8c57-3c327eeb4c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfRelease</value>
         <variableId>1d64916c-27ae-4c7d-b471-b872dff09c35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>scheduleUnitReleaseDate</value>
         <variableId>13281907-eb91-455b-b210-4bf877477894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualUnitReleaseDate</value>
         <variableId>68264b98-57f2-46d8-97d6-78f6abd52cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentType</value>
         <variableId>55981167-f0a6-4029-8833-e3c62d756e1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentFrequecy</value>
         <variableId>f3cc6c4f-53b1-4f4a-8eb8-99d9d61585e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfPayment</value>
         <variableId>8092ce41-2be0-405f-9b27-b75e0bd0ea49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>effectiveDateOfAda</value>
         <variableId>f401b8a3-5544-4c6b-8e3d-728ab654dbd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountNumber</value>
         <variableId>df09e952-ec66-420e-ada0-3099d6546b1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountName</value>
         <variableId>d788b0b4-e6d1-4e17-90b8-b48c4b4bd8f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2667fd52-7ecb-411a-b587-c4841e1cf6be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DocumentChecklistForPreReleasePaperbasedNSTP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>689e396d-6276-4a13-ab12-d7d306745faa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/CollateralInformationForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7f3c48-f7dc-436d-a3a2-3d6c54bba095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c924381-06e9-4798-b837-ebbc854b0094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>715eca79-7ae2-4cdd-b1f9-74739f12e1f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73bb284c-7dfb-49ac-b395-c660171b187b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>db2b1549-d132-44ff-bed0-a98f9a1a4285</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>986c9d24-515b-4c68-ae28-1e58238a31ff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPostData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>986c9d24-515b-4c68-ae28-1e58238a31ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>986c9d24-515b-4c68-ae28-1e58238a31ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>279fe0d8-3371-43fe-8507-04ef72dcdef7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/PostReleaseSubmit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
