<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>8445629f-fc1d-4485-a400-259e178a2b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Additional_Info_Next_BTN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Borrower_Continue_BTN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3ce80dd-7ae2-498a-96bb-18a78c83f094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.OnClickBorrowerDetails){OnClickBorrowerDetails(this,event);}</value>
      <webElementGuid>3a0831f9-5987-4576-bbba-1048add6cc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer</value>
      <webElementGuid>182d29af-9de5-468e-8377-8a9f968d91c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>862faacd-7d67-489a-b5a4-f0a64b8d2451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Borrower_Continue_BTN</value>
      <webElementGuid>18a5e495-6d7d-45bd-9bc4-7156606614bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Borrower_Continue_BTN</value>
      <webElementGuid>3673749f-f1f4-4748-bb82-8a361eaaac6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue</value>
      <webElementGuid>b4d0e293-3b51-4829-b85a-378555c3bb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Borrower_Continue_BTN&quot;)</value>
      <webElementGuid>147623e8-fd97-4b9c-a44b-159e62edfba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Frames/iframe_Form_ngformIframe</value>
      <webElementGuid>1bf1e6a0-b2a8-4c48-a86d-1c989c1c7aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Borrower_Continue_BTN']</value>
      <webElementGuid>82617bfc-3103-43a6-a938-9d93174263f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustMinInfo_frame1']/div/div/div[14]/div[3]/div/button</value>
      <webElementGuid>a862b525-6d03-4ded-b784-236baac98d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>ec6e46e4-f63b-4b27-bce5-4fa853a2ba25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save &amp; Exit'])[1]/following::button[2]</value>
      <webElementGuid>ad6f33ff-99e3-42fd-9bdd-e4c0facd1898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidden_JSON_Data'])[1]/preceding::button[1]</value>
      <webElementGuid>e8225395-146a-4b1a-840a-b301aeae8aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[6]/preceding::button[1]</value>
      <webElementGuid>47a63ccf-a808-4f12-abce-ddf2714cd333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>6d42e7b0-6e6a-4898-9c7d-0c3c9b84155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[3]/div/button</value>
      <webElementGuid>a0a69e8f-62fc-4520-b422-a587c46bb10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'Borrower_Continue_BTN' and @id = 'Borrower_Continue_BTN' and (text() = ' Continue' or . = ' Continue')]</value>
      <webElementGuid>b83b1e5a-6a92-4101-a00e-24d9cb87f9a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
