<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carBrand</name>
   <tag></tag>
   <elementGuidId>cb9edd45-8378-4ad1-8c28-5ce8bb6984f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CL_Car_Brand']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CL_Car_Brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf453b4d-47ce-4c96-9b95-e55c1b34d133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>7251e1d7-5d8c-4aac-9666-8958394176fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CL_Car_Brand</value>
      <webElementGuid>1126be86-5980-40c9-9464-e539745cba83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CL_Car_Brand</value>
      <webElementGuid>3fa25bd9-e96c-49bd-bf84-fcf866b13d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Car_Brand</value>
      <webElementGuid>be9a6267-3f49-464e-a400-12d420d7ae50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>6fddc49c-d50b-4555-afbc-748046476d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5dbd7aa6-a8ac-4c24-b3fc-9e7c0e4208b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.Car_Brand</value>
      <webElementGuid>05f4a3bc-092d-4ed7-b30e-4d920d1cb94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeCarBrand){onChangeCarBrand(this,event);}</value>
      <webElementGuid>a2e11ada-e054-40c6-9026-4c1482391013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>e2931ecd-ab0b-4802-8e13-a27765f20071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectANFRA</value>
      <webElementGuid>00f68b4b-2587-4fb2-9842-5514586f361b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CL_Car_Brand&quot;)</value>
      <webElementGuid>cc071f11-5ef4-4636-95a4-7d0f9c5c2b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>229c3024-c926-403a-8aa6-23a254f75989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CL_Car_Brand']</value>
      <webElementGuid>8d31aad4-dc8d-418c-93df-2c1aff6b8dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div[4]/div/div/div/select</value>
      <webElementGuid>032d560d-a9ec-47b5-a4d7-b02e8b9fd5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[155]/following::select[1]</value>
      <webElementGuid>6c597195-6fb4-43a5-92f2-e8c0bcb815e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Condition'])[1]/following::select[1]</value>
      <webElementGuid>3885ebb4-1516-45cb-a2e1-187ef81b8672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Brand'])[1]/preceding::select[1]</value>
      <webElementGuid>68bc85da-ac74-4900-accd-4b294049d1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[156]/preceding::select[1]</value>
      <webElementGuid>4b07e167-b448-4309-b66f-cd7be5988eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[4]/div/div/div/select</value>
      <webElementGuid>ee19d767-963b-4c46-a0af-2623373c8a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CL_Car_Brand' and @name = 'QL_CollateralInformation_Car_Brand' and (text() = 'SelectANFRA' or . = 'SelectANFRA')]</value>
      <webElementGuid>43fb32ca-9dab-4c51-8435-a26023b38d7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
