<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CarCondition</name>
   <tag></tag>
   <elementGuidId>cce2ca64-848b-4913-baec-929d86ba5816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_CollateralInformation_Car_Condition']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#QL_CollateralInformation_Car_Condition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdfd2f58-b16a-4546-aad9-be0a9eecbf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>e71a2efe-5752-44c5-8aa2-3bc374e76715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Car_Condition</value>
      <webElementGuid>8f8457ad-1e92-4ae7-85b3-fe6cf3b6cc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Car_Condition</value>
      <webElementGuid>1e7891f1-ae4b-4030-aa09-b8f6fb76d1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Car_Condition</value>
      <webElementGuid>2c89b446-8e75-4540-9003-052094289e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>9cd1c690-5dd8-426b-881e-bf7451d9fe5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f82c8470-28b3-4071-b255-e3f87545a592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.Car_Condition</value>
      <webElementGuid>8b5b0aae-df56-4339-99c6-90a45916b53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>0f4cf2f5-287b-46f4-8525-7c7fc20cce7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>693a190e-e884-40ec-add8-3f00a5402b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectBrand NewUsed</value>
      <webElementGuid>abd16967-e88b-4b86-96ff-a6cd5eb29352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_CollateralInformation_Car_Condition&quot;)</value>
      <webElementGuid>0e6d3a2c-cdd9-40f5-b5de-52f86da16ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>87e2512d-a9da-4bb1-aa79-07912bfdd5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_CollateralInformation_Car_Condition']</value>
      <webElementGuid>ebadaade-7d58-4d17-86bd-eb4f2d2a501c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div[3]/div/div/div/select</value>
      <webElementGuid>0e924bd8-da95-4faa-9a26-7d2681422115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[154]/following::select[1]</value>
      <webElementGuid>97872323-1c55-44b1-8b99-b60e50eec299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[48]/following::select[1]</value>
      <webElementGuid>a9fab888-c637-487e-8458-533cd46f403e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Condition'])[1]/preceding::select[1]</value>
      <webElementGuid>8ef4ab64-ef5f-475e-a85a-33cb92dfb152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[155]/preceding::select[1]</value>
      <webElementGuid>bbfc9611-7dcc-49b8-85df-325debd0c881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[3]/div/div/div/select</value>
      <webElementGuid>c19f1f42-62c5-40d0-b4c3-0f79a9b57c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'QL_CollateralInformation_Car_Condition' and @name = 'QL_CollateralInformation_Car_Condition' and (text() = 'SelectBrand NewUsed' or . = 'SelectBrand NewUsed')]</value>
      <webElementGuid>b7a75041-6dc2-46f9-9828-cd8b054f0309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
