<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>carModel</name>
   <tag></tag>
   <elementGuidId>6d2a6b85-07d9-4d3c-be71-17ea76a1b2e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CL_Car_Model']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CL_Car_Model</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2d73b6bc-8f1c-4006-8a04-676efc655e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>024374d6-0a5e-4bd1-a5ae-2d0bb9d56e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CL_Car_Model</value>
      <webElementGuid>b5766d27-cc40-47ef-9d55-dfd019c8d345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CL_Car_Model</value>
      <webElementGuid>108e2115-b051-4b9f-b9b9-21b5d565dfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Car_Model</value>
      <webElementGuid>41af6d5d-562d-469e-9782-3be1341eb9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>082c33aa-d1ab-4372-8ca1-0fcc26878454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ef937bf8-1106-44a4-abf0-c06edefdf9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.Car_Model</value>
      <webElementGuid>ce71fdc7-c010-4a7d-90e0-0f03135062cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeCarModel){onChangeCarModel(this,event);}</value>
      <webElementGuid>21f3c3b1-e15b-4a77-931e-8e6c86ca435c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>9644d26c-a7dc-47f8-88d0-74ed8cb8f62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectTRANSPORTER</value>
      <webElementGuid>c11beca7-543e-4fb9-84b9-68b489e496fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CL_Car_Model&quot;)</value>
      <webElementGuid>9429af25-f694-44d5-8f36-9062d3696d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>0277f39b-2c50-4d66-a28c-718624774ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CL_Car_Model']</value>
      <webElementGuid>4e3efdf0-75a1-4a7b-9dae-8d223b45aab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div[5]/div/div/div/select</value>
      <webElementGuid>e12af0cf-92bf-4653-97d6-38c7e2e96ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[156]/following::select[1]</value>
      <webElementGuid>f65f1b8f-beac-4101-9fc3-379b7fb8ab69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Brand'])[1]/following::select[1]</value>
      <webElementGuid>db5bc012-99e2-42a8-a961-faf66e81dfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Model'])[1]/preceding::select[1]</value>
      <webElementGuid>478f4910-3595-40ec-bcd0-a933cc9cfe8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[157]/preceding::select[1]</value>
      <webElementGuid>577968cd-9d51-4884-88e6-d9bd9a166381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[5]/div/div/div/select</value>
      <webElementGuid>31ba4b5b-7d44-4b03-8474-21a1b58f5d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CL_Car_Model' and @name = 'QL_CollateralInformation_Car_Model' and (text() = 'SelectTRANSPORTER' or . = 'SelectTRANSPORTER')]</value>
      <webElementGuid>44b618df-37f6-468f-819c-7c670b458a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
