<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>28fda7b2-838d-41ea-8de3-9bec6462d357</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ngformIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3300a947-a9f5-40da-a9fb-7be18abc834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>5d29ffb3-e278-4e44-b198-1517d6997a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000514&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000514&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=e952ff9e-3e2d-458d-9cdc-7fe682adb9d2&amp;WD_RID=056e1413-2616-4cd9-9258-94f2285bb721&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=fd1393fb-f483-48b0-b3d2-a5c043ba3f37&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>e3174509-645b-4c63-8beb-c53bd84538cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>ba2813eb-a9d9-460c-ae2a-0f8725b93e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab8e71bd-6511-4616-86d2-e9c15cf29aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>288ca449-cac7-451e-9ccf-b99a6f8b3644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9e9661d3-473b-4a37-8a46-f565b65d820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>2b651349-f4b3-475d-a75e-23a3530d2443</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>44189762-4c05-4f96-9789-37ec05dca34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>3fd4b57c-9a4c-4917-80b1-83906c092d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>81323bde-59cb-4a11-b53c-1c72ea78491c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000514&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000514&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=e952ff9e-3e2d-458d-9cdc-7fe682adb9d2&amp;WD_RID=056e1413-2616-4cd9-9258-94f2285bb721&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=fd1393fb-f483-48b0-b3d2-a5c043ba3f37&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>987fe8fc-1a55-40df-9d4e-478ed0406854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
