<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>makeType</name>
   <tag></tag>
   <elementGuidId>48997dcb-33ee-48ed-9769-32943543c6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CL_Make_Type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CL_Make_Type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3b0cfa2b-647a-4a17-86df-2ea7ccbe0b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>36f3a441-01ff-4c32-9396-de5c3833ca89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CL_Make_Type</value>
      <webElementGuid>d8a9982b-fba1-4d1d-9677-73b137c57ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CL_Make_Type</value>
      <webElementGuid>b5a57ce7-3030-42ac-a07c-b513b67084c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Make_Type</value>
      <webElementGuid>e92bb23d-0c4e-4840-a7c8-dac7d758597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>0a2479bb-eae1-4c46-ac6e-037119f187a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>6ddb9a46-be45-4905-8d2a-2a9e32031b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.Make_Type</value>
      <webElementGuid>2afbd34c-321c-497a-8ffc-bb85c7b22668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeMakeType){onChangeMakeType(this,event);}</value>
      <webElementGuid>e61c2861-4df8-49fb-b18a-aa3c5088e748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>444c6eac-ac0d-48d0-aa5e-3c86fe8b9e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectVAN</value>
      <webElementGuid>a6f88961-b031-48f8-84ba-669565beb73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CL_Make_Type&quot;)</value>
      <webElementGuid>6b53dcf0-2762-45e5-a774-2868a85be43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>24f2afd9-acc7-46f6-b064-b2dd9258ce14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CL_Make_Type']</value>
      <webElementGuid>dbe4accd-cb42-4ae6-83a6-3f44cc0bb0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div[8]/div/div/div/select</value>
      <webElementGuid>52c9eeb8-d933-4664-aadf-ffb17e1c8aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[159]/following::select[1]</value>
      <webElementGuid>362c75d2-a3ec-4a00-9220-925fdb8e571d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year Model'])[1]/following::select[1]</value>
      <webElementGuid>7d70bc40-396d-412b-8d24-ac5bbffa7fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make/Type'])[1]/preceding::select[1]</value>
      <webElementGuid>35369e93-39be-42d6-b5f0-746863db8c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[160]/preceding::select[1]</value>
      <webElementGuid>f9db5e17-7a07-45fd-8a4e-7ffc4d42b62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/select</value>
      <webElementGuid>766d96a4-1586-4fcf-ab88-e8fe26d76f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CL_Make_Type' and @name = 'QL_CollateralInformation_Make_Type' and (text() = 'SelectVAN' or . = 'SelectVAN')]</value>
      <webElementGuid>3c3eaf70-5d67-4a58-a3a6-98273374df8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
