<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>subModel</name>
   <tag></tag>
   <elementGuidId>59f0c1de-4f31-4e76-9776-53ef9d6a4df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CL_Sub_Model']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CL_Sub_Model</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66b3bace-eb8f-4939-947d-a293687f615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>5e44a393-e6e0-4bcd-94e4-39118277075a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CL_Sub_Model</value>
      <webElementGuid>e87042d0-25cd-47b1-bbd0-d2bc2beb8464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CL_Sub_Model</value>
      <webElementGuid>574cedab-982c-4527-aba9-f98e723f4919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_SubModel</value>
      <webElementGuid>75db6b02-c0de-467f-86bf-07c41b53e350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>b5d9a594-c324-4036-8d2b-8ebedf5b0671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>87da2a78-efb7-4573-b52d-64fe2c20737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.SubModel</value>
      <webElementGuid>464d25b8-92da-4db7-ad4a-1a419d9ab491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeSubModel){onChangeSubModel(this,event);}</value>
      <webElementGuid>a794b7b1-77f7-4025-a34f-6651599ec502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>e978ca96-a8f9-4885-b3ec-e3366a48d2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectSWB</value>
      <webElementGuid>677748c7-ee97-47c1-85e6-9faf272ae98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CL_Sub_Model&quot;)</value>
      <webElementGuid>6fd2889e-9498-4fab-9dd8-cc1e8e838bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>7a40e1d2-8e78-4679-93d1-0cceb1a1d01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CL_Sub_Model']</value>
      <webElementGuid>9307c22e-db11-4141-add4-792c953c755b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div[6]/div/div/div/select</value>
      <webElementGuid>55f754a2-0ab0-4464-b630-d6fed3c539c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[157]/following::select[1]</value>
      <webElementGuid>cf7965b9-d251-4325-8e01-addcb2f6dfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Model'])[1]/following::select[1]</value>
      <webElementGuid>c6c4de6b-8a93-4dec-90d5-2013eace5974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubModel'])[1]/preceding::select[1]</value>
      <webElementGuid>c972c05f-a54e-45c8-abdd-bd1bbd888e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[158]/preceding::select[1]</value>
      <webElementGuid>ee8f790a-8a90-4456-b698-5302d95fe5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>299b3d81-11eb-41d3-bfa5-ec9426a5fb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CL_Sub_Model' and @name = 'QL_CollateralInformation_SubModel' and (text() = 'SelectSWB' or . = 'SelectSWB')]</value>
      <webElementGuid>8e6e68fe-2450-462e-91ec-0ff1a7918464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
