<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vehicleCodeType</name>
   <tag></tag>
   <elementGuidId>82c962da-35b2-4a33-b962-9942fe1a8c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_CollateralInformation_Vehicle_Code_Type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#QL_CollateralInformation_Vehicle_Code_Type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbb4ccee-dd90-447f-8deb-6dac910b43e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>108f3a08-00e7-4d31-80eb-2cca66b9fa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Vehicle_Code_Type</value>
      <webElementGuid>515799bd-c98a-4b69-b04f-b4cbf2665fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ANF004</value>
      <webElementGuid>a7c50852-b631-4fa3-8673-c105cd5be39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Vehicle_Code_Type</value>
      <webElementGuid>f226a4d5-a665-4ba8-a889-264c7ce3f58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_CollateralInformation_Vehicle_Code_Type</value>
      <webElementGuid>8a8d9948-a34f-420d-be74-fa3893ebe842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>9fedd823-93dc-410a-a0b0-74ea9358061b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>76caa7a7-b1f0-4602-bb7e-ae6774c9bb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_CollateralInformation.Vehicle_Code_Type</value>
      <webElementGuid>44e4a3f5-b5d0-4694-bc5a-b5eb5a7085ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeVehicleType){onChangeVehicleType(this,event);}</value>
      <webElementGuid>043fcf59-1e4d-4475-9d3a-95e9ccbe2a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>9ed5b34e-92c6-43aa-a277-69d8c83b9f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectALFA01ANF004AUA411BM2101CHCP06FOFS05HNHR20</value>
      <webElementGuid>8faae818-2940-499d-b58f-077e8c9aa677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_CollateralInformation_Vehicle_Code_Type&quot;)</value>
      <webElementGuid>d54fcc96-c7a9-437d-b046-34e78c92cf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderCollateralInfoPaperbase/iframe_Form_ngformIframe</value>
      <webElementGuid>655327f1-f2ca-419b-891d-2922866712df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_CollateralInformation_Vehicle_Code_Type']</value>
      <webElementGuid>fe2ce2d1-a3d2-4357-b405-a2dfabd79dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame768']/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>f53fc8f4-e76d-4dec-bbaa-e5e5f39cf66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collateral Information'])[2]/following::select[1]</value>
      <webElementGuid>e623a857-c0f7-4497-8f63-48e96eb093c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[152]/following::select[1]</value>
      <webElementGuid>8333a322-8266-4fa5-a6fa-0d245f4f9fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Code/Type'])[1]/preceding::select[1]</value>
      <webElementGuid>51d78312-b4ca-49ac-bf1d-4bdd4cb74d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[153]/preceding::select[1]</value>
      <webElementGuid>446c54b0-ff7d-4219-923e-a5aad7520a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>fc1df621-baf5-4433-ab5b-92016fff7a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'ANF004' and @id = 'QL_CollateralInformation_Vehicle_Code_Type' and @name = 'QL_CollateralInformation_Vehicle_Code_Type' and (text() = 'SelectALFA01ANF004AUA411BM2101CHCP06FOFS05HNHR20' or . = 'SelectALFA01ANF004AUA411BM2101CHCP06FOFS05HNHR20')]</value>
      <webElementGuid>0def5d66-cde9-46a8-8df6-87ddd8bf07bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
