<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Collateral Information</name>
   <tag></tag>
   <elementGuidId>14e75535-1d3b-47bd-879f-c70b9a38466d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sheet131_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet131_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc022feb-da2f-4d2d-8d93-678c756c2283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Collateral Information</value>
      <webElementGuid>5c042a76-28b4-4bc4-96ac-96b9beb3cf82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>48247aef-efc1-4916-a6db-de0d81b0bfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>7b5b1907-28a4-4d55-a7df-76ea5d534fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>63daf1e8-d494-4057-b49f-ab688c42b49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet131</value>
      <webElementGuid>0174417a-371a-4d4c-88d1-ad555662885f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet131_link</value>
      <webElementGuid>aa328e7c-cdf8-4ab8-a333-5977eea2c5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfafb476-c0da-48ca-986d-ea7a915bf42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>59e5e5a3-25a5-4545-a06f-6df7b95a30bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collateral Information</value>
      <webElementGuid>484f5f4c-401a-4c32-b3fd-e53dff6f5ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet131_link&quot;)</value>
      <webElementGuid>e231f77c-db63-4987-961c-f9b35426a07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostReleaseObject/Page_Dealer Post Release/iframe_Form_ngformIframe</value>
      <webElementGuid>a44abf33-863c-4491-a8e6-9bc954782a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet131_link']</value>
      <webElementGuid>e5fdec5d-81b3-47eb-8661-c55bd94f194e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[5]/a</value>
      <webElementGuid>f98f185b-fa47-4697-bb6b-3c73f0b42f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Collateral Information')]</value>
      <webElementGuid>3f33b83a-597a-46c1-9d0b-5f7f635a9b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Eligibility'])[1]/following::a[1]</value>
      <webElementGuid>b304d833-9188-49da-ab02-78e5a53f8c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Checklist'])[1]/following::a[2]</value>
      <webElementGuid>f91616f2-d3ed-472e-807b-faa2935e3765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Evaluation'])[1]/preceding::a[1]</value>
      <webElementGuid>c50850c2-b48b-4302-b1a8-f080cc63724b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deviations'])[1]/preceding::a[2]</value>
      <webElementGuid>d51c7d55-1700-4490-a220-b22ed3f267c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Collateral Information']/parent::*</value>
      <webElementGuid>b54d0a17-279f-49e3-8521-9339d550e08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet131')]</value>
      <webElementGuid>95abf1e7-7c7e-4bfa-8e14-f3fa2ede3495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>80fe48fd-07ad-4728-b980-7ace83263a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Collateral Information' and @href = '#sheet131' and @id = 'sheet131_link' and (text() = 'Collateral Information' or . = 'Collateral Information')]</value>
      <webElementGuid>f83e8d20-9a86-458f-b3c1-f727ac5abddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
