<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Disbursement Information</name>
   <tag></tag>
   <elementGuidId>6a6fbe4e-02bf-4fd4-8f65-2273c2e60726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sheet137_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet137_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05bae93a-25a5-40b5-9b6e-babb687cca52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Disbursement Information</value>
      <webElementGuid>c7cccf8e-55b0-4ce1-8da5-c036450d8f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>a7f05a97-05d2-4ccc-8419-7e9e8a3f7bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>7679768c-2d4d-4d76-978b-b66808449134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1dc5de32-cf45-4d09-8ab6-0fe07b87b6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet137</value>
      <webElementGuid>825a5acb-b61d-4aa6-bf97-6d9808ffb81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet137_link</value>
      <webElementGuid>a130c552-ae53-4f84-b91d-f47e4d80835b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0432b2f2-89e4-4e96-8bab-721629b544e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>93a42c6b-d1cf-4de4-8fe6-543a86a078b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disbursement Information</value>
      <webElementGuid>1d96709e-8d96-4bb7-a152-f72524012d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet137_link&quot;)</value>
      <webElementGuid>afeb4984-4fd2-48e8-8b19-3182977136aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostReleaseObject/Page_Dealer Post Release/iframe_Form_ngformIframe</value>
      <webElementGuid>4be8da73-d9b6-489e-9ba8-a044440f608a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet137_link']</value>
      <webElementGuid>6309bad8-b363-408f-a857-d412a734a4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>5f9d0b77-d9f1-4f56-a364-ae766eddeb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Disbursement Information')]</value>
      <webElementGuid>5a324422-f611-48cc-b029-d31af9712619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance Information'])[1]/following::a[1]</value>
      <webElementGuid>ba7527bb-1fbe-46ab-8ca1-1c65a0d5d81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Investigation'])[1]/following::a[2]</value>
      <webElementGuid>2cc2e535-21dc-4c53-98a6-4ff0419c1ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Interfaces Status'])[1]/preceding::a[1]</value>
      <webElementGuid>e54f2bd5-55c1-49f2-80f2-0f8055824a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts Summary'])[1]/preceding::a[2]</value>
      <webElementGuid>9639324a-8b70-4453-a5e3-d5bc25f173d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disbursement Information']/parent::*</value>
      <webElementGuid>34169eb0-9f04-4a37-8d60-9a4feaca8c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet137')]</value>
      <webElementGuid>7b48089b-00df-4d07-9807-36c28997c61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>89bda54e-eada-4d7f-8fbb-bf340b7459e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Disbursement Information' and @href = '#sheet137' and @id = 'sheet137_link' and (text() = 'Disbursement Information' or . = 'Disbursement Information')]</value>
      <webElementGuid>c6b72988-526e-4f9d-a725-8e4f17b90396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
