<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Document Checklist</name>
   <tag></tag>
   <elementGuidId>edc7611a-ada5-4156-a820-9d0063a6f9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sheet130_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet130_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7d34bea-4d87-4079-8d30-ff54aa166827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Document Checklist</value>
      <webElementGuid>f7e435d4-3af6-4b71-bad3-97e25a6ef7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>9fd3b02b-67ea-4aa4-a5da-e5490978a5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>4945f90d-4f28-4773-9e66-8f2886125a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fcdf2c04-344c-4ad2-8cf6-1cf258422343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet130</value>
      <webElementGuid>e5d9d719-fcdb-4132-afc0-c3e1aa434f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet130_link</value>
      <webElementGuid>91ab2f11-65fd-4ec2-9d08-ee5b47a18f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f80eba4-e848-42cb-8b4c-fb01d32e15e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cbecc235-e394-46ed-8854-7cab072615ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document Checklist</value>
      <webElementGuid>5fe760c1-e215-41e1-b464-ec7c7559dc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet130_link&quot;)</value>
      <webElementGuid>037de552-c4fa-4098-be88-855ec0b148d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/PostReleaseObject/Page_Dealer Post Release/iframe_Form_ngformIframe</value>
      <webElementGuid>5348af4f-fb1a-436e-8596-78cfdf896ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet130_link']</value>
      <webElementGuid>d628176e-4146-4204-b8f0-4b67533c4f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>9704fc82-2c00-42e7-a42d-9f9c20011088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Document Checklist')]</value>
      <webElementGuid>52f643f9-e67c-43f3-8095-1c0b89ab7ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Information'])[1]/following::a[1]</value>
      <webElementGuid>d1014c5f-716f-40e2-a1f0-3f5328533832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Information'])[1]/following::a[2]</value>
      <webElementGuid>ce4f4b5f-e7f7-47d0-844b-dd484118c9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Eligibility'])[1]/preceding::a[1]</value>
      <webElementGuid>183d3a39-56f4-417c-821b-786ffceb2104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collateral Information'])[1]/preceding::a[2]</value>
      <webElementGuid>cf203f95-d5c2-4b94-bd6a-6c01c34b4002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Document Checklist']/parent::*</value>
      <webElementGuid>39cd1a5c-c390-49e2-8b76-59619e7fed89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet130')]</value>
      <webElementGuid>8d86fadb-41c4-49d2-84ff-cd5ad86e2814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>c320c259-95f2-4f87-b6dd-c3a8126527f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Document Checklist' and @href = '#sheet130' and @id = 'sheet130_link' and (text() = 'Document Checklist' or . = 'Document Checklist')]</value>
      <webElementGuid>a80934e7-2655-40ff-b919-845676f4be80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
