<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>4bd91b2d-2669-4065-9d4c-7e6a9c007be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-1000002114&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-1000002114&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=4&amp;WD_SID=32ad3d59-c66b-4633-b64b-1860f97f7332&amp;WD_RID=f471fe57-db45-4f0e-a5a0-379f9c140238&amp;FormBufferFolder=rcbcdev_1_4&amp;FormBufferName=14&amp;fid=Form&amp;rid=ea5e1c18-5b08-4a58-9024-65e058b951b6&amp;ArchivalMode=N&amp;mobileMode=']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[13]/div[1]/div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>38879851-a5a2-4f2a-a302-cc29e64cc2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>8934e337-f31f-4222-acc0-bf8ebc0781f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-1000002114&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-1000002114&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=4&amp;WD_SID=32ad3d59-c66b-4633-b64b-1860f97f7332&amp;WD_RID=f471fe57-db45-4f0e-a5a0-379f9c140238&amp;FormBufferFolder=rcbcdev_1_4&amp;FormBufferName=14&amp;fid=Form&amp;rid=ea5e1c18-5b08-4a58-9024-65e058b951b6&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>1da6bd0d-3153-4a50-b783-b679cbdc72b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>dee4f01a-16ec-4150-bcfd-7363d3fbef62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf2dc636-2d95-4688-a78c-57ebc939f845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f16eb71d-b09b-4aa1-9fb4-ca7bb6f074b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ca2f26f-2adf-4a6d-9120-296c2bf5be94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>5e62edfd-efbd-46b7-9d59-3d57a0c84b9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>917ef631-0c43-4585-8640-8a8998e01967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>6c43b841-58ef-4db4-8436-a25424cccd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>d5c8bebc-d677-4149-bf1b-1bffa23cec52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-1000002114&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-1000002114&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=4&amp;WD_SID=32ad3d59-c66b-4633-b64b-1860f97f7332&amp;WD_RID=f471fe57-db45-4f0e-a5a0-379f9c140238&amp;FormBufferFolder=rcbcdev_1_4&amp;FormBufferName=14&amp;fid=Form&amp;rid=ea5e1c18-5b08-4a58-9024-65e058b951b6&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>371f9412-780b-4a54-8178-a976f0bfcdf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
