<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>borrowerGrossMonthlyIncome</name>
   <tag></tag>
   <elementGuidId>cd267fe0-07ef-406e-be8f-de8300390796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BorrowerGrossMonthlyIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BorrowerGrossMonthlyIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46a3e1d9-5694-426e-87b4-c681c6c6b250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>43c0bcad-2ada-414b-8448-3215c10b4ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4ed7197-5849-4d37-8988-de28aa38ad32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e387b06-25a0-4267-b063-d14d1510b648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>2e86924a-4dd0-44d9-bb86-e75377808762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BorrowerGrossMonthlyIncome</value>
      <webElementGuid>c07d9c79-6294-4318-9ff6-1e9ad986a642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_Borrower_Gross_Monthly_Income</value>
      <webElementGuid>8aa02267-90ca-4f95-ad5d-aa68a66047c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.Borrower_Gross_Monthly_Income</value>
      <webElementGuid>14e97c58-34c2-4289-9ef7-c68f7e4844b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>a76b3197-fa35-48bf-9b4f-a574f64c021b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>7d72fcf7-a3de-49f2-9b2f-40f1631665d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>55e9beb4-b4e7-4306-93e7-e02706b87c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'2','BorrowerGrossMonthlyIncome')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'BorrowerGrossMonthlyIncome');</value>
      <webElementGuid>d6e3a4b9-128b-4e95-9c85-57df0a50da03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>888b356c-e52c-4532-b435-6a913bf3bf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.CombinedGMIval){CombinedGMIval(this,event);}</value>
      <webElementGuid>ebf3e7dd-8947-44d7-8af9-19875eab743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>32aaae83-2198-4c08-b1a0-0fe5899a4c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c12e6903-d7cf-41a7-8f3e-5728a3829899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox mandatory</value>
      <webElementGuid>f5ae61c3-f709-4414-a9e5-987d203bc788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6492b876-2999-42cd-9f88-bbd4354dca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custommasking</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8455d97-93e9-4474-96ad-bde7fe905f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BorrowerGrossMonthlyIncome&quot;)</value>
      <webElementGuid>8bbb6bd6-691e-41dc-ae4e-bf2712548553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>8a150fa6-bd12-47bb-9b6d-5207737be433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BorrowerGrossMonthlyIncome']</value>
      <webElementGuid>1a0e957e-8e26-46b4-b211-1fb8fac19f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame825']/div[2]/div/div[4]/div/div/div/input</value>
      <webElementGuid>b8425d2f-cc38-4e9e-8a6f-b98ba3b53724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/div/div[4]/div/div/div/input</value>
      <webElementGuid>116935f6-c332-4f77-88bf-135cced91c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BorrowerGrossMonthlyIncome' and @name = 'QL_VouchingInput_Borrower_Gross_Monthly_Income' and @type = 'text']</value>
      <webElementGuid>63884774-efce-4603-ab75-32087ad2891b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
