<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Co-BorrowerGrossMonthlyIncome</name>
   <tag></tag>
   <elementGuidId>8bd508a5-1fa5-4692-bdcc-65f7675e49fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CoBorrowerGrossMonthlyIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CoBorrowerGrossMonthlyIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5922e724-795a-47d3-a5c1-e218b912cb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>8b7c1018-2f44-44b2-bed4-d9b71344a3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b433db3b-c0e5-4e3a-a42c-315424ff197e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>36b2b048-ba47-4e61-a0b5-6aa2b7971f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>aab8d3f5-3112-4999-9805-73f0d3aa247a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoBorrowerGrossMonthlyIncome</value>
      <webElementGuid>e03e986d-be5c-4672-b270-d8e75c831a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_Co_Borrower_Gross_Monthly_Income</value>
      <webElementGuid>98b6502b-6bd4-4130-a1e8-91d8d49bd161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.Co_Borrower_Gross_Monthly_Income</value>
      <webElementGuid>57400d84-f333-4239-861a-8e5f58ef099d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>80cd2bbf-1723-404e-bd34-d6542b838715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>1775ac32-84f8-447a-a7e1-da20d65e9936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>732b39ae-39aa-4350-95f3-fa5a2cb3e2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'2','CoBorrowerGrossMonthlyIncome')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'CoBorrowerGrossMonthlyIncome');</value>
      <webElementGuid>d2f48532-1d38-4756-9aeb-e6ca24765197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>ba352b2c-1338-4210-aa7a-01bf094c3d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.CombinedGMIval){CombinedGMIval(this,event);}</value>
      <webElementGuid>b15c03f7-68cc-4c32-9ce4-9860045b74dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>9ae18060-ed56-457d-b758-0409c36c252b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d44bc989-6227-49f3-bd67-0cc7d7b00ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox mandatory</value>
      <webElementGuid>1826ed3d-03f6-4ced-b223-f21986ca2a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>663ba9e9-cb1c-41ba-8ca7-931ab33b191c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custommasking</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87d41148-5700-49ac-8e17-ee78140cf3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoBorrowerGrossMonthlyIncome&quot;)</value>
      <webElementGuid>801785ab-aade-48de-b8dd-470e9a7ee31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>2ce02a95-14df-4f3d-b57d-32cf2a6b6eac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CoBorrowerGrossMonthlyIncome']</value>
      <webElementGuid>2cbb351a-3663-4246-875b-baeceedce015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame825']/div[2]/div/div[6]/div/div/div/input</value>
      <webElementGuid>73b226f6-e71b-47c9-981d-171c56b4f585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/div/div[6]/div/div/div/input</value>
      <webElementGuid>ac38fb7f-2d71-4670-8145-c892de498c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CoBorrowerGrossMonthlyIncome' and @name = 'QL_VouchingInput_Co_Borrower_Gross_Monthly_Income' and @type = 'text']</value>
      <webElementGuid>1ce82ab3-650a-47af-99e2-cbcbbb4e5604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
