<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateOfBirth</name>
   <tag></tag>
   <elementGuidId>b7cd9085-a928-4e9a-9208-bf5537a18817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BorrowerSpouseDateofBirth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BorrowerSpouseDateofBirth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b778da22-b44c-4f8f-8b37-c4cfc18763b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>calculatespouseAgeMaturity</value>
      <webElementGuid>83f1c4df-5a33-44a0-9f0c-928085ee7295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>00/00/0000</value>
      <webElementGuid>68d7d39b-109a-4743-9ff5-f9e78e2eb788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>BorrowerSpouseDateofBirth</value>
      <webElementGuid>e2678b65-d597-4b94-a13a-4029057877a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>a6d4cc71-8da7-4731-9ea0-903a4f0b5222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b61798a9-0d24-426f-8012-0270b1ccec7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BorrowerSpouseDateofBirth</value>
      <webElementGuid>0ad60b9d-0821-40cc-b393-829da701c75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_B_spouse_Date_of_Birth</value>
      <webElementGuid>f11497a4-e3a0-4a59-985c-35bbdce6c27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.B_spouse_Date_of_Birth</value>
      <webElementGuid>0d9a7f35-6fe2-4a77-abfc-718c249bd768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f64c640-b1a5-44bd-b43f-e9a45666531e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>dbce5b6e-912c-44e0-b9af-efd72b59536b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-input mydatepicker inputStyle input-focus</value>
      <webElementGuid>6dacad54-0440-4476-94a1-9fa07374a792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dateformat</name>
      <type>Main</type>
      <value>1_1_1</value>
      <webElementGuid>b4041211-b380-41bb-81db-7738206cf51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>modifyClass(this); attachDateRange(this);</value>
      <webElementGuid>3178ce31-108e-448e-809a-8a3cf77a5de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>07/02/1996</value>
      <webElementGuid>7cab7052-9f58-48ec-b243-7ed98d53f889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BorrowerSpouseDateofBirth&quot;)</value>
      <webElementGuid>313908ff-cc7c-4cde-b1da-90735809dfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>63f2eb02-10fb-42f9-af17-faaf7316532c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BorrowerSpouseDateofBirth']</value>
      <webElementGuid>ca357763-7fd9-4c1d-9a6d-0e86756cd23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame824']/div[2]/div/div[20]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>2a01d808-a28e-4c9f-ab25-c7e4508ad6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>524363c1-6d42-4fd1-a335-f9a2c4b4960a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BorrowerSpouseDateofBirth' and @name = 'QL_VouchingInput_B_spouse_Date_of_Birth' and @type = 'text' and @title = '07/02/1996']</value>
      <webElementGuid>554effed-3a85-4851-b1e5-4932985567c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
