<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>09d7dd2b-b3f2-47d7-be94-8678f9290240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ngformIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>97f6f984-e560-4dc9-a6b7-c44069812bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>8bc06318-8095-4306-bf35-047110919079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000001469&amp;wdesk%3Awid=4&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000001469&amp;WorkitemID=4&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=92&amp;WD_SID=76f2aa6a-6888-44b1-8662-0a1ae03ab0f4&amp;WD_RID=1bbe9e14-1a23-41c7-9471-ca8d996f3b34&amp;FormBufferFolder=rcbcuat_1_92&amp;FormBufferName=14&amp;fid=Form&amp;rid=bb829773-7229-4f0d-9274-d3da0b102e82&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>88b878bd-0e86-4c85-9481-725ced0b074a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>fa63b4ad-3b0e-46a2-8714-b1d7c8ed4a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1bf51ae-b003-4ae1-930e-4208995c2c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1dc38f4-37ae-4bb8-bef5-95f15a118fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8cef7f36-1269-424b-8aa3-2e2a6aab45b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>498824b2-c680-4c32-8009-fb4b20fcbf4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>f6937eb3-c33a-441f-abc1-a47497a9fc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>effd81ec-d4b7-4679-abf7-891b0e61aab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>9beb79f9-5c15-4ed3-ac5f-0c40a104c2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000001469&amp;wdesk%3Awid=4&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000001469&amp;WorkitemID=4&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=92&amp;WD_SID=76f2aa6a-6888-44b1-8662-0a1ae03ab0f4&amp;WD_RID=1bbe9e14-1a23-41c7-9471-ca8d996f3b34&amp;FormBufferFolder=rcbcuat_1_92&amp;FormBufferName=14&amp;fid=Form&amp;rid=bb829773-7229-4f0d-9274-d3da0b102e82&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>b7fb2a95-7c0c-4de5-be07-f6a9c7c01612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
