<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>residenceCategory</name>
   <tag></tag>
   <elementGuidId>8162cc8e-f3eb-4301-b1c0-c38bed00ff1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_VouchingInput_Residence_Category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_VouchingInput_Residence_Category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bcc5a29-6421-4a1c-9bc1-b666a0a5e487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>2619984e-7bbe-459d-aac0-bad10e27df98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_VouchingInput_Residence_Category</value>
      <webElementGuid>7410e8df-2254-4bf3-aa21-1794f869c6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aligned Variant</value>
      <webElementGuid>42954057-9c7a-47dd-94f8-e442f35c41a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_VouchingInput_Residence_Category</value>
      <webElementGuid>51febe3b-a489-45cd-af00-b067092823c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_Residence_Category</value>
      <webElementGuid>e77e452a-9b10-44ef-8b89-3e9f90b26aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>66f0be7d-bbbc-4b93-938b-657b93723574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>35d81ac6-fdf5-4c08-b1b5-00e4014036f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.Residence_Category</value>
      <webElementGuid>fbb63a8d-2b15-42bb-ae07-a68d7fa66959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>22552f06-6126-4d19-9121-a9a5eddb0eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>dc33ba20-a2c2-409b-8b42-0ddd5ead5369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand</value>
      <webElementGuid>5a613bd1-8c6d-4fe8-a72e-f41dde7e11a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_VouchingInput_Residence_Category&quot;)</value>
      <webElementGuid>e7c712a2-1518-40bd-9fef-12d87d5a0d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>fe5e9007-0e50-4869-80cd-7b423c1bcae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_VouchingInput_Residence_Category']</value>
      <webElementGuid>bf968092-15ed-466b-bf3f-cad2126ab214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame824']/div[2]/div/div[10]/div/div/div/select</value>
      <webElementGuid>b2958481-7d3d-4b80-8496-291c003461f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[297]/following::select[1]</value>
      <webElementGuid>b4191bb3-9335-419f-ad04-dcb9c9662fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AS'])[1]/following::select[1]</value>
      <webElementGuid>e9f8fe3c-09db-4d52-9c3a-f7a1b346e53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Residence Category'])[1]/preceding::select[1]</value>
      <webElementGuid>ff91bff9-0ddf-46a3-b6df-65f3b4dfecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[298]/preceding::select[1]</value>
      <webElementGuid>2ad36468-a7f0-4766-89f5-289cbb391075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/div[2]/div/div[10]/div/div/div/select</value>
      <webElementGuid>6bc7a41d-66af-4d80-9973-c3a98ad964c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Aligned Variant' and @id = 'QL_VouchingInput_Residence_Category' and @name = 'QL_VouchingInput_Residence_Category' and (text() = 'SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand' or . = 'SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand')]</value>
      <webElementGuid>d566e8c7-6b55-4a4f-b8f8-a2a5a9842ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
