<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spouseGrossMonthlyIncome</name>
   <tag></tag>
   <elementGuidId>2f80bd37-a257-42fe-8a01-b64593ae1095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SpouseGrossMonthlyIncome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SpouseGrossMonthlyIncome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5942de9-fa0a-4648-a22d-e8daaa534702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>c81deceb-2571-49f1-8de9-cecde48c9b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6039711a-f926-433f-a3b1-dac3dbc7b75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>da5cc959-2997-4bdd-a790-50f4bfd385e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>3c2253ee-061c-4a74-b103-f4a712492062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SpouseGrossMonthlyIncome</value>
      <webElementGuid>edacfb8f-7e37-4d41-9a2a-831abdbbf576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_Spouse_Gross_Monthly_Income</value>
      <webElementGuid>756d7f13-89ad-4b25-8ea3-55eaf8231bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.Spouse_Gross_Monthly_Income</value>
      <webElementGuid>330f1a4e-c2e9-4085-a2f9-9fa281281de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>df37e604-e6c7-4282-a44c-be073783a4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>48093541-0995-4347-8e15-049594394614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>19a2f1bd-faaf-4bec-81f2-4b4b71d954c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'2','SpouseGrossMonthlyIncome')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'SpouseGrossMonthlyIncome');</value>
      <webElementGuid>bfbc3375-c838-4fe2-a656-a17158aa3e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>1cbd8211-134c-4fe9-936c-6594aed90158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.CombinedGMIval){CombinedGMIval(this,event);}</value>
      <webElementGuid>fb271ba2-db9e-44c9-9213-402c4fcd674e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>779662a4-48fc-409f-9356-9066a654177c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0a8f5e6-c8db-4f23-88ce-881d5610df09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox mandatory</value>
      <webElementGuid>d1f45db9-ee23-41dc-8278-ba6d418d6c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>56582e2e-4333-4aa8-870a-86026b6778a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custommasking</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b003ff2d-564e-41cc-9ebf-bae253c0581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SpouseGrossMonthlyIncome&quot;)</value>
      <webElementGuid>242bb2cf-19c6-47d5-bf73-106432a4632d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>d9c6cc14-f546-4dba-b012-caf1e6093bf1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SpouseGrossMonthlyIncome']</value>
      <webElementGuid>bba76923-91bc-4717-8025-0f8fd78338ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame825']/div[2]/div/div[5]/div/div/div/input</value>
      <webElementGuid>1013d170-1e1f-483f-aa8a-f7b2621bf723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/div/div[5]/div/div/div/input</value>
      <webElementGuid>01b42a6b-b4ac-4376-b583-92d2359861f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SpouseGrossMonthlyIncome' and @name = 'QL_VouchingInput_Spouse_Gross_Monthly_Income' and @type = 'text']</value>
      <webElementGuid>7e49604b-0bd5-484e-a8f6-67c4a6bfd067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
