<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vehicleCategory</name>
   <tag></tag>
   <elementGuidId>a20bfdb4-cbd4-46ce-b163-8fcd49b95801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LoanVehicleCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LoanVehicleCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f47d334-9fe0-425b-9349-750ce581de92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>acc2b2d2-fcc9-4283-b620-34941992e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>LoanVehicleCategory</value>
      <webElementGuid>f6f0b29d-53ee-406f-8de8-5b819453973a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoanVehicleCategory</value>
      <webElementGuid>7370de76-eb60-4c0d-96e2-eaa85e1693fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_VouchingInput_Vehicle_Category</value>
      <webElementGuid>ff5e7db0-8cdd-4183-b27d-2f10b7ae5eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>8b966678-8856-4714-bbc3-333bb51b2c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9ab67fd5-5e06-449a-af8e-d98b152cee2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_VouchingInput.Vehicle_Category</value>
      <webElementGuid>8ad8b5b9-5381-4f1d-a49d-9bfbe4471bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>b4e98da9-9412-4533-b54b-4b12604071ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>b01be607-4dc1-4572-80be-4da0d98a2643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand</value>
      <webElementGuid>a28f4ec1-31e0-4801-b1d8-3b4403eba1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoanVehicleCategory&quot;)</value>
      <webElementGuid>bcdf82d3-fcac-4a8e-8f08-f2064affdc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SDApprover/VouchingInSDApprover/iframe_Form_ngformIframe</value>
      <webElementGuid>73965676-c0d2-4e48-a4c9-fb177abb47d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LoanVehicleCategory']</value>
      <webElementGuid>d84daa7e-4165-45f3-80b9-5309c1a56580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame826']/div[2]/div/div[6]/div/div/div/select</value>
      <webElementGuid>672203f9-f10f-491a-8655-d25cb92a67bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[325]/following::select[1]</value>
      <webElementGuid>f608bf78-44f3-4ad7-a88f-885247ff1469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[106]/following::select[1]</value>
      <webElementGuid>ad608bb9-c216-47a0-8df5-54c4101ea2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vechicle Category'])[1]/preceding::select[1]</value>
      <webElementGuid>a22f183a-05c7-4a04-bf75-3767ea6c964e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[326]/preceding::select[1]</value>
      <webElementGuid>3111a717-4a61-4ae1-a0a9-e09ed4d77f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[6]/div/div/div/select</value>
      <webElementGuid>30199cf7-9a02-4a17-999c-22d1b67682c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LoanVehicleCategory' and @name = 'QL_VouchingInput_Vehicle_Category' and (text() = 'SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand' or . = 'SelectAligned VariantFull SedanPreferred VariantReputable BrandSmall SedanTop Brand')]</value>
      <webElementGuid>2ade4315-8277-460a-a30e-1b1c06097646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
