<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NSTPPreChangesActualCashout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e8793d6c-4d37-4d16-9970-1c84f072e892</testSuiteGuid>
   <testCaseLink>
      <guid>f8042499-0dc4-4ac4-8ba4-4136b473277d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Digital_STPWithAndWithoutAPI/DigitalPotal/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2425ed3a-03d7-4e40-b981-591d9d590d7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForManageLoanPreAndPost/homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f71b59ec-738d-482b-9244-ad7077dc887f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a88d8796-03ab-41a7-8fca-dabdecb989a6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a88d8796-03ab-41a7-8fca-dabdecb989a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a88d8796-03ab-41a7-8fca-dabdecb989a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6aca23b-229e-446c-8ddc-8bcdcdf7302e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/CustomerDetailForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e5f675e0-e0c4-4ffa-ad23-86e4814195fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DigitalVouchingAndAmendmentInNSTP/PrereleaseChanges/LoanInformationForPreRelease</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>983f3906-d8cb-4bca-82dc-aa744cc32181</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInformationForPreRelease</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marketingPromoCode</value>
         <variableId>b4cbdccd-74a5-4bd3-8463-54189bd00445</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanPurpose</value>
         <variableId>99c7fb1d-1029-4e59-847a-e326843aec78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfRelease</value>
         <variableId>65b21c0b-d4db-4531-9d6d-ca1aaad76717</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>scheduleUnitReleaseDate</value>
         <variableId>378f2528-61d4-4baf-93ab-d8a27c5081b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualUnitReleaseDate</value>
         <variableId>84003326-ecb2-41ff-949a-fe51817e78d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentType</value>
         <variableId>0947363e-dc9d-4436-b52d-3d9a2e564aaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentFrequecy</value>
         <variableId>bd7d83e8-db55-45ec-b252-c8e7ff13ebd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfPayment</value>
         <variableId>59afb500-bd16-491b-8a01-4d79d8079067</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>effectiveDateOfAda</value>
         <variableId>8287ca9a-5b6f-4ce6-b2ea-b9c4e3516eaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountNumber</value>
         <variableId>e02cd8b6-888a-4ea1-b5fc-b23197cedbd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>983f3906-d8cb-4bca-82dc-aa744cc32181</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountName</value>
         <variableId>eb748d20-c833-43ff-b3bb-83bd1a4c1ade</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2667fd52-7ecb-411a-b587-c4841e1cf6be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DocumentChecklistForPreReleasePaperbasedNSTP</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>689e396d-6276-4a13-ab12-d7d306745faa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/CollateralInformationForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7f3c48-f7dc-436d-a3a2-3d6c54bba095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c924381-06e9-4798-b837-ebbc854b0094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>715eca79-7ae2-4cdd-b1f9-74739f12e1f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73bb284c-7dfb-49ac-b395-c660171b187b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>db2b1549-d132-44ff-bed0-a98f9a1a4285</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Base_Scripts/TestCaseForPreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>986c9d24-515b-4c68-ae28-1e58238a31ff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPostData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>986c9d24-515b-4c68-ae28-1e58238a31ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>af30113b-81a4-47fc-badb-cbb347acd1d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>986c9d24-515b-4c68-ae28-1e58238a31ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>7c438659-261b-4040-a509-eec3fd080cf5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
