<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PortalForWithoutSTP</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1065f1d9-3718-4f6f-9831-b5ea286ee7a2</testSuiteGuid>
   <testCaseLink>
      <guid>f7477f4a-e326-4dcc-877a-6a5a43cb594e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3bf43079-52a0-4d9e-8352-49dd6832e6d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/HomePage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>048472c1-3763-4f86-954c-fbb180370738</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/SelectAutoLoan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>466bd277-c36a-47b8-8b3a-88c82de43ddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/LetsgetStarted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1a0b4fec-7df2-4503-8ffd-91ee0942294b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/LoanDetails</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>18df9469-21d8-4e7f-8263-cc4f2fc94c90</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInfoForWithoutAPI</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>brand</value>
         <variableId>516ae9d2-66b1-49e2-82ba-ae041feaf6d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>unitDescription</value>
         <variableId>5c4af6cf-19ed-4320-ae70-84bf00be6157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanTerm</value>
         <variableId>05c76392-f2c1-496a-95af-9d67d24b2d56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>downpaymentValue</value>
         <variableId>4ac414de-39f0-49c8-ba59-b6ca9ac1be7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualCashOut</value>
         <variableId>2300eb04-6691-4c27-9a79-dc82eee18e6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18df9469-21d8-4e7f-8263-cc4f2fc94c90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>insuranceType</value>
         <variableId>89c3ab18-b656-4a95-92c8-47aaa15df189</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a228973a-b1f3-4818-87f9-a350c550a095</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/BorrowerDetail</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5428d71f-dee9-4365-afd2-bc3fa07aad96</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/BorrowerDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fst_Name</value>
         <variableId>3547196b-acf8-44fe-8633-25ef43a9c67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mid_Name</value>
         <variableId>3ce1aa62-f4e0-4f68-9b15-109df3e33dea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>lst_Name</value>
         <variableId>cd043b82-ddee-479a-aaf5-b6e359a2eadf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>suffix</value>
         <variableId>0c1fd109-1703-4557-a545-5121ad07ba68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>maritalStatus</value>
         <variableId>7caa9f3a-53b0-40d7-8869-3752fdc16091</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>8d0f8526-6eea-4cfa-a15f-f799c21e33b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>d90ec5c8-301e-4d4a-8e69-cf281409a517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mob_Num</value>
         <variableId>7f1ab8ed-6348-4bf3-b46e-e3972674b47f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5428d71f-dee9-4365-afd2-bc3fa07aad96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>residence</value>
         <variableId>83a33d8c-0498-4c3b-a347-60c2f360185a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0983134d-6e8f-4cd7-9640-130a5d6629f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/ConfirmationPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0dfe621c-2eac-48e8-ba53-f8aa9fffe6d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/InitalCheckingWithoutAPIPrequalified</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9e7d9fbd-508f-42ba-870b-7ed933d04f3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/AdditionalPageWithoutAPI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fe58e744-3628-4d43-839f-e7f4be2f7cb3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AddiDataForCoBorrowerAPI</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>fe58e744-3628-4d43-839f-e7f4be2f7cb3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerRelationshipWithBorrower</value>
         <variableId>78b88c0e-c2d8-43bd-8eae-1f7b25881d93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fe58e744-3628-4d43-839f-e7f4be2f7cb3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerFirstName</value>
         <variableId>6e7d4ca3-224e-411d-8383-16b5ceb8e0fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fe58e744-3628-4d43-839f-e7f4be2f7cb3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerMiddleName</value>
         <variableId>6a2e3ba0-39d9-433b-ae8d-4f458799a8da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fe58e744-3628-4d43-839f-e7f4be2f7cb3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerLastName</value>
         <variableId>dafe3740-4f8a-4695-b6fa-39c41fe5c385</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fe58e744-3628-4d43-839f-e7f4be2f7cb3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>coBorrowerSuffix</value>
         <variableId>4c9d06b9-73d9-43ac-bd1c-2ec0cd16291c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5754cdfc-bf10-4efc-8dff-a25d0ab3e6c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/DocumentUploadPageWithout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cabffd2d-8f10-474d-b467-f188a6096cb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PortalForWithAndWithoutSTP/submitpagesuccessForWithoutAPI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
