<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PreAndPost</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c837cb33-c226-4f8a-a6ef-17b31a55bfe9</testSuiteGuid>
   <testCaseLink>
      <guid>380728b6-5a30-4f72-bb1e-80242184e34f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b398f307-0756-422a-b001-b2e7a44e6c35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0a3346ba-5089-48d7-af13-52b7890ddf1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2a3dfe59-47c2-42ff-9ed8-be51d819a9ae</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2a3dfe59-47c2-42ff-9ed8-be51d819a9ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>477b161b-5fbe-45ad-8b01-c8d7e3137933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2a3dfe59-47c2-42ff-9ed8-be51d819a9ae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>da6f00d0-5c1c-4df0-b42d-0c71bcd02979</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22341045-7756-433c-bad9-6569d48ae35b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/CustomerDetailForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a504e232-2999-4c26-a69a-76242afa55a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/LoanInformationForPreRelease</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ce89c0eb-c935-45d2-81af-10235d55d008</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/loanInformationForPreRelease</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marketingPromoCode</value>
         <variableId>0b5d8899-3102-4fc6-bcf1-2d2dd7518eb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanPurpose</value>
         <variableId>6808d4b3-9896-4054-a55b-8d959fb6fc35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfRelease</value>
         <variableId>60f090be-e6ab-4085-975b-272c1cef4a05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>scheduleUnitReleaseDate</value>
         <variableId>ed7d4970-b878-4a85-b201-75549c44beec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actualUnitReleaseDate</value>
         <variableId>aad04aa1-2ffa-499d-b070-b82cec795b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentType</value>
         <variableId>01084124-38c0-432a-84da-d543176fcf1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>paymentFrequecy</value>
         <variableId>4a0b1b09-3a17-4351-88e2-9bdd1bab3cd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfPayment</value>
         <variableId>355b983e-2b00-43bc-8feb-28adade5e79f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>effectiveDateOfAda</value>
         <variableId>37768e9b-a2a7-42c6-8358-a915b0c5b5d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountNumber</value>
         <variableId>75c5e96c-a2b5-4c8a-ab24-1206672bef54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce89c0eb-c935-45d2-81af-10235d55d008</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>accountName</value>
         <variableId>883617e2-712f-4a36-9445-6c672f0c7b2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86474a4f-7c46-45bc-8886-18b2420a1b49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/DocumentCheckListForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fcfae3a3-786d-495f-a3da-92373890c5c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/CollateralInformationForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e2c47f1-2675-4b88-b2b7-ed75c74075e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f800aeee-3ce4-4079-9d93-73471231e274</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc0b6ef-88ca-46a7-b6c7-2267b4d9b67f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d90963ca-2890-41f0-8c39-bcca91b75679</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4875f3ab-19c9-4de8-9fcb-06f45b239c80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>db449db0-0cb7-43dd-ad9d-6831f3f6fcf3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPostData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>db449db0-0cb7-43dd-ad9d-6831f3f6fcf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>477b161b-5fbe-45ad-8b01-c8d7e3137933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>db449db0-0cb7-43dd-ad9d-6831f3f6fcf3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>da6f00d0-5c1c-4df0-b42d-0c71bcd02979</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4df61a36-f120-482e-afab-3ad1a76f1311</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AOAsDealer/Digital/WithAndWithoutSTP/PreAndPost/PostReleaseSubmit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
