<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Disbursement Information</name>
   <tag></tag>
   <elementGuidId>1974a915-9a9a-4d0f-9a22-82067f29bcfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet137_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sheet137_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Disbursement Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0731a52-91a6-4806-a472-d625f4da6267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Disbursement Information</value>
      <webElementGuid>b02a1810-a7e8-4625-9e9d-920b68af09bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>017a6205-0137-43cd-ae49-9d8e55bec21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>0fb80971-807e-41b8-9200-2549b3838d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9f889301-047e-46f2-b46f-7f258335ff6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet137</value>
      <webElementGuid>48dd9f0e-7a86-4f4b-b85b-7be5fd8c772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet137_link</value>
      <webElementGuid>90266566-c74f-4585-8529-6a75d930611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f573f39-5610-4deb-b1cd-f6e4b6d75b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>660920fb-ca29-4874-89f7-e69dda1103b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disbursement Information</value>
      <webElementGuid>2931c428-af3d-4d95-aab1-c7937cfef6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet137_link&quot;)</value>
      <webElementGuid>37c83ebf-fa00-40e1-9322-16c4b3d49ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/newRocorder/Page_Dealer Pre Release  LOS-1000004176/iframe_Form_ngformIframe</value>
      <webElementGuid>cb3e2672-8072-40e0-a45e-3f1c09166c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet137_link']</value>
      <webElementGuid>fcf9a4a6-9ff3-46c3-814f-9f76f300b8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>ac2969d2-33d3-4495-9a28-0b989a1a9e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Disbursement Information')]</value>
      <webElementGuid>c9aba0a8-b17a-4683-83f9-3541558c13d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance Information'])[1]/following::a[1]</value>
      <webElementGuid>47b5716a-ddcb-445d-b14d-08f89dd1a80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Investigation'])[1]/following::a[2]</value>
      <webElementGuid>aaa991fd-4df8-46f6-b220-c3a5c0a3178b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Interfaces Status'])[1]/preceding::a[1]</value>
      <webElementGuid>33e396a6-0a27-4545-af4d-268f5820ac35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alerts Summary'])[1]/preceding::a[2]</value>
      <webElementGuid>4b127aa6-978e-45e0-b870-58f8dc826702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disbursement Information']/parent::*</value>
      <webElementGuid>6af65467-5ee2-4272-b203-f7555e651519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet137')]</value>
      <webElementGuid>30c956d0-db6d-4e15-9f92-344b3d98c5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>0767e5b2-cc15-4679-a0e4-cd79535f508c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Disbursement Information' and @href = '#sheet137' and @id = 'sheet137_link' and (text() = 'Disbursement Information' or . = 'Disbursement Information')]</value>
      <webElementGuid>8b33ce67-a3a4-4198-b07b-949db81b4154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
