<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Document Checklist</name>
   <tag></tag>
   <elementGuidId>a3efe0ed-ac6b-4d5a-abad-949128e35668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet130_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sheet130_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Document Checklist&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de8c8982-2eb1-4fcc-afcf-dcc76e3397dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Document Checklist</value>
      <webElementGuid>7fe7cb70-6730-494f-9b33-459c1c4a3b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>3e57fe07-98cd-4f54-8e6f-e7c0b8d15430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>846f900a-2245-4fb0-8055-6cc61ec79927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0c781fae-8aa5-4ab2-be4f-05a3b0c04c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet130</value>
      <webElementGuid>917e4067-edfb-471f-bcdc-89b10899e0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet130_link</value>
      <webElementGuid>835f1a70-65b5-45f1-a046-f950545d5468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6cdb4c0-645f-471a-93a3-0660c72bf713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a5037ad0-deb6-4e39-969a-3cbee257b04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document Checklist</value>
      <webElementGuid>4d0c0017-57f6-4cbe-8592-cc94deb17042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet130_link&quot;)</value>
      <webElementGuid>43e11e5b-5bed-4117-b218-ddaa83282d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/newRocorder/Page_Dealer Pre Release  LOS-1000004176/iframe_Form_ngformIframe</value>
      <webElementGuid>66f5ac43-c8f9-4a1a-977c-c7c22cb472f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet130_link']</value>
      <webElementGuid>7e0d2193-941e-42d4-9cd9-030f0e806b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>a170e506-1d48-4604-9a49-bd30c9f8de6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Document Checklist')]</value>
      <webElementGuid>cd27a908-e774-46c8-83b4-5db21d87c8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Information'])[1]/following::a[1]</value>
      <webElementGuid>5f72ae0e-f735-4537-be42-edb4653fd051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Information'])[1]/following::a[2]</value>
      <webElementGuid>843bd460-6967-4557-8866-a00d5ff46bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collateral Information'])[1]/preceding::a[1]</value>
      <webElementGuid>fc11ada1-6330-4a87-8c15-fb55283a8dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Eligibility'])[1]/preceding::a[2]</value>
      <webElementGuid>28691d63-99b2-4253-8dc8-f5aa298f558a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Document Checklist']/parent::*</value>
      <webElementGuid>70b01f3f-6bfd-4896-bfdb-de362edf00bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet130')]</value>
      <webElementGuid>d3219432-b3ac-4b50-8e44-07b2b6e4e46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>7aa0091d-a7bf-454b-b00e-35f9625ca6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Document Checklist' and @href = '#sheet130' and @id = 'sheet130_link' and (text() = 'Document Checklist' or . = 'Document Checklist')]</value>
      <webElementGuid>44a1e151-a04e-471e-b755-1bf64cbccaa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
