<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Loan Information</name>
   <tag></tag>
   <elementGuidId>cc78494b-eee5-4853-9110-5d179d90ce41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sheet129_link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sheet129_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Loan Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad3a337c-5fb8-4292-bdc3-d5cc6500a908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Loan Information</value>
      <webElementGuid>4bc9ca30-eab7-439c-a813-01618795e393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabStyle nav-link tabSheetLink tabhyperlink tabtheme2 active</value>
      <webElementGuid>3a52547f-cfdb-4aa5-8b63-00a8d7e561ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>5e78507d-3332-4d27-8eb7-014788414415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>88a1acc1-da7f-4f25-b855-dacde3de3795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sheet129</value>
      <webElementGuid>8a0859c5-49c4-498e-90c0-a6b742ba465b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sheet129_link</value>
      <webElementGuid>d2c85093-3258-4b4e-8c69-54c99bcd8073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d844ac3-ce0e-4be4-8839-94b0e7264827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e672a37b-f77c-4973-be4c-8a45b137d1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan Information</value>
      <webElementGuid>33f2fc13-e720-4d9b-b5de-03f97a2ab654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sheet129_link&quot;)</value>
      <webElementGuid>f1605119-afcb-44ee-8dfe-e5b237cd949d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/newRocorder/Page_Dealer Pre Release  LOS-1000004176/iframe_Form_ngformIframe</value>
      <webElementGuid>85f502a9-2ae3-4368-bf8f-d7ed858c7909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sheet129_link']</value>
      <webElementGuid>ce47c07b-a15b-4732-892b-6ebc8f4a7999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab82']/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>216970b3-1e16-4f35-9b22-7ccda9c9bbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Loan Information')]</value>
      <webElementGuid>f2140ea7-07d9-43ac-9d9d-fbd8c0d86c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Information'])[1]/following::a[1]</value>
      <webElementGuid>359ea226-0f1e-4895-9d43-f76e50b06131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booking'])[1]/following::a[2]</value>
      <webElementGuid>56159868-67d7-46bb-8f96-d3af0b446861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Checklist'])[1]/preceding::a[1]</value>
      <webElementGuid>67e8f044-f576-4fee-8298-215d656ffc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collateral Information'])[1]/preceding::a[2]</value>
      <webElementGuid>11ff447c-4da9-4cb8-8185-9c4ecb6f785d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loan Information']/parent::*</value>
      <webElementGuid>6a5ae5db-e81a-44b1-919b-d891b1286c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sheet129')]</value>
      <webElementGuid>905cd564-593a-4728-956d-d7d856eef777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b0956aa2-4f9d-4c7c-83b5-aea11c93dbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = ' Loan Information' and @href = '#sheet129' and @id = 'sheet129_link' and (text() = 'Loan Information' or . = 'Loan Information')]</value>
      <webElementGuid>b540e7eb-0f66-406b-87dd-8b68db88fd72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
