<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>401cb2ba-3d78-4f1b-9306-ca738afcef29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ngformIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ngformIframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9c614ca1-965b-4fd2-a390-64fed45baae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>df117f18-96c3-4d7c-8309-f4a0077c50ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-1000004176&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-1000004176&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=2&amp;WD_SID=6fe30fef-8bb6-4b03-af6f-8532c3b1693b&amp;WD_RID=a0c52f9f-725c-4ef8-a448-9689980feec2&amp;FormBufferFolder=rcbcdev_1_2&amp;FormBufferName=14&amp;fid=Form&amp;rid=acb582e7-c803-4a10-a6fb-796aa3ca9203&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>b939ee11-36f9-4c75-8685-1193a0d08310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>24dd3aca-2605-4f52-a7f0-b1d59a38722d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>93aabb7d-1d23-47c2-9f4e-c7198aeb876f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>94a8c29a-a6ba-46b5-ad8a-dd0a2aab8159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1f73032-5c0d-478a-95dd-881e3e3f1da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>1e53eda9-334d-4dfe-a78b-d534649bf797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>7f081fe8-0106-42ea-b9b2-4dc903fbb603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>7a45bd82-6fd0-40f9-ac70-ed88f54d3372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>28d67d1a-a137-46f3-9f39-a7f9a7d39fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-1000004176&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-1000004176&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=2&amp;WD_SID=6fe30fef-8bb6-4b03-af6f-8532c3b1693b&amp;WD_RID=a0c52f9f-725c-4ef8-a448-9689980feec2&amp;FormBufferFolder=rcbcdev_1_2&amp;FormBufferName=14&amp;fid=Form&amp;rid=acb582e7-c803-4a10-a6fb-796aa3ca9203&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>ecf35858-f2f6-466b-b598-9eae85e5858d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
