<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SelectSubmitCancel</name>
   <tag></tag>
   <elementGuidId>5873bb18-255a-48d3-a01b-79783cad4e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DecisionValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DecisionValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SelectSubmitCancel&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4577c2fb-6224-4f7b-9bb3-9dfd403871d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>79a66ef0-4814-4bbe-a748-013b96499aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>DecisionValue</value>
      <webElementGuid>63e0dc90-166d-45f7-bc16-4861a99fb1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DecisionValue</value>
      <webElementGuid>a617596f-a1fa-45b0-a1f1-f23b648c30e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DecisionValue</value>
      <webElementGuid>c094b7ac-30cd-4d2c-aa72-d09e9d8444de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>d822ea39-3f18-42be-a3fe-9b176b3c0a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>40f870bb-daa0-4fb1-9c66-ad7f112a75fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onDesChange){onDesChange(this,event);}</value>
      <webElementGuid>cc0d00ca-7858-42bc-8a9d-b24703ac2154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle  </value>
      <webElementGuid>80b8adab-432a-426e-b903-15ae2a8b43cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectSubmitCancel</value>
      <webElementGuid>bf71a5de-b381-4222-8ab6-9d6fec1e9083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DecisionValue&quot;)</value>
      <webElementGuid>1ca231ff-6b20-41b7-88a7-4a6acf8e33d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/newRocorder/Page_Dealer Pre Release  LOS-1000004176/iframe_Form_ngformIframe</value>
      <webElementGuid>c4c639a8-456c-4e3d-9823-0d269649248f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DecisionValue']</value>
      <webElementGuid>b9b89eae-22e1-454b-bf49-271bb3507715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='F_Decision']/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>9ce80fa8-eba8-47df-b440-db216eed0e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decision Details'])[1]/following::select[1]</value>
      <webElementGuid>877190e1-02f8-439a-bb6f-16dd4acf6568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/following::select[1]</value>
      <webElementGuid>08f94008-3bc2-40d0-a514-a727d1c82df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decision'])[1]/preceding::select[1]</value>
      <webElementGuid>5c40fee9-017c-4abb-b132-638856ce63f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[346]/preceding::select[1]</value>
      <webElementGuid>6cfea8dc-ea39-43f2-b22d-156f748a51f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/div/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>582693d1-213b-4eb4-9944-f1b5296a899e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DecisionValue' and @name = 'DecisionValue' and (text() = 'SelectSubmitCancel' or . = 'SelectSubmitCancel')]</value>
      <webElementGuid>61c2f1ce-c2ff-4e69-b527-a6740e85e0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
