<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_For applying auto loan</name>
   <tag></tag>
   <elementGuidId>af61d626-b219-4f7b-a8a4-93f26511edb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Tile3-true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Tile3-true</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;For applying auto loan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b29731bb-8ffb-44b3-bcb9-ed6dd98bb664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4136b749-9002-4897-94b2-55a99e7523dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tile3-true</value>
      <webElementGuid>43fd6fe1-a398-4a4e-bc8a-1d296276bbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83d7cc86-3910-484d-9796-e86c36d7ecf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tilestyle</name>
      <type>Main</type>
      <value>Style1</value>
      <webElementGuid>7375c5ff-4101-4ac4-a12f-e3fbce419600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tile</value>
      <webElementGuid>b451ee6c-d8a8-4a38-896e-24b9868174b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openNavigationForm(1,this);if(window.onAutoLoanPortalClick){onAutoLoanPortalClick(this,event);}executeCommand(event,document.getElementById('Tile3'),'%5B%7B%22eventType%22:%22Click%22%2C%22parameters%22:%7B%22FormName%22:%22NavPage%22%2C%22DecisionField%22:%22textbox2%22%7D%2C%22command%22:%22RouteJourney%22%7D%5D');ctrOnchangeHandler(this,1);</value>
      <webElementGuid>4cbe8b96-bfe2-453c-92c8-41bdd1c55580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-button-select tilebtnstyle </value>
      <webElementGuid>f35f7b8c-c8e5-46fb-97e2-6ec017436d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For applying auto loan</value>
      <webElementGuid>bfc2360e-3e91-49ca-aa42-88f96e2a45ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tile3-true&quot;)</value>
      <webElementGuid>e6652641-8b59-4092-b2ac-9e44c82a124c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Tile3-true']</value>
      <webElementGuid>82355eef-945b-4eb6-9f78-1a3c1a16fa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Tile3']/div/div[3]/button</value>
      <webElementGuid>a565d428-18d7-450d-9cf3-f2455c31bbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Loan Portal'])[1]/following::button[1]</value>
      <webElementGuid>450539ae-f113-427f-be25-ab79993cf344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECTED'])[2]/following::button[1]</value>
      <webElementGuid>20bfc3c9-0716-4306-b575-324d25dda178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[2]/preceding::button[1]</value>
      <webElementGuid>e066a1b1-906c-41ea-9fef-2e5ca138d115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECTED'])[3]/preceding::button[2]</value>
      <webElementGuid>1e0394f6-3c02-4cfa-b553-0af2e791e3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For applying auto loan']/parent::*</value>
      <webElementGuid>835372e7-7805-4ac9-993e-8f89253e7194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>b8f6e6e0-0b95-40d4-84bc-3fe911c6c7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Tile3-true' and @type = 'tile' and (text() = 'For applying auto loan' or . = 'For applying auto loan')]</value>
      <webElementGuid>8f528d80-2df8-4079-bf28-14700fbb2486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
