<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log In</name>
   <tag></tag>
   <elementGuidId>fa544a6f-041e-464f-9196-1448862e6cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LoginBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Log In&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35e0fca0-b060-4801-b70b-5dbe10cb7704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginBtn</value>
      <webElementGuid>eea0bf8e-2681-477f-ae27-083f09011cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginBtn</value>
      <webElementGuid>19adcbc7-cda0-44dc-941d-7ce288b67d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84be68d1-81b4-4b1c-a792-8416f73668da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer </value>
      <webElementGuid>9c1901eb-6caf-444d-aef3-c9c56e7471ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onloginclick){onloginclick(this,event);}executeCommand(event,this,'%5B%7B%22eventType%22:%22Click%22%2C%22parameters%22:%7B%22IsCaptchaEnabled%22:%22false%22%2C%22UserName%22:%22textbox1%22%2C%22CaptchaControl%22:%22%22%2C%22FormName%22:%22LandingPagePopup%22%2C%22UserAuth%22:%22textbox2%22%2C%22AuthenticationType%22:%22iBPS%22%7D%2C%22command%22:%22RouteCriteria%22%7D%5D');</value>
      <webElementGuid>484226b3-35c5-46a0-aed5-fa1cc0ea9078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log In</value>
      <webElementGuid>e36f4c65-dfee-4b94-8eb8-a92c1ed308dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginBtn&quot;)</value>
      <webElementGuid>87bbc03b-e7f9-4d05-8eb4-58487a721ae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='LoginBtn']</value>
      <webElementGuid>d270352c-a035-4a8c-ab4b-66c6e8828d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame1']/div/div/div[10]/div/button</value>
      <webElementGuid>b6c253ea-eb4a-4865-9d4c-3713ed8530c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[2]/following::button[1]</value>
      <webElementGuid>3e034325-1363-4dde-8ceb-7613c0fe36e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password'])[1]/following::button[1]</value>
      <webElementGuid>37610843-963d-4c4c-886f-33df404d2320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='textbox3'])[1]/preceding::button[1]</value>
      <webElementGuid>b48a091c-d4c3-4f33-b729-1ee45d351af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[3]/preceding::button[1]</value>
      <webElementGuid>624c256b-64fd-485e-a705-6cb0be0e5022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>cb2a28da-e07f-41f7-a737-01a2812a6ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>2d470dd8-07d3-4d2d-bacd-5209df3a3e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'LoginBtn' and @name = 'LoginBtn' and @type = 'button' and (text() = ' Log In' or . = ' Log In')]</value>
      <webElementGuid>7d974a13-31ba-48f1-9c3f-3dbe3cacf15b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
