<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ff8ce2f9-1d79-412f-8f6a-6bbe49d8cc82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='LVcloseButton']/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LVcloseButton > span > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LVcloseButton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b36b39fc-8749-40ac-8d83-8dcf2bc3a9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./resources/images/normal-cross.png</value>
      <webElementGuid>9902824a-e312-49bb-9901-f62d04fc6350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15px</value>
      <webElementGuid>ba9ffda4-4e5b-4405-b042-2d114d9b1863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15px</value>
      <webElementGuid>c179120f-2203-4e7e-a0ae-3b42e75a9484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LVcloseButton&quot;)/span[1]/img[1]</value>
      <webElementGuid>0368d9d3-74c6-4040-b1bb-66831c9fc654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='LVcloseButton']/span/img</value>
      <webElementGuid>7623e6d6-ab1a-46af-9f32-690f79076cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/button/span/img</value>
      <webElementGuid>8b8994a0-d227-4f78-9390-629289e400e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './resources/images/normal-cross.png']</value>
      <webElementGuid>e60085de-0dcb-4b09-9269-fec44ae4b8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
