<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All ApplicationDealer Pre ReleaseDea_4ef469</name>
   <tag></tag>
   <elementGuidId>ee1c9348-5069-4672-b543-5d258f215045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='stagename']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stagename</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14ec4a48-1fa2-41d4-b1cd-86ab114395f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>ce3af822-6b84-49e0-93f2-96bfe7e54d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>308be4d1-cff7-4c7b-b41f-a108e7c48be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Application</value>
      <webElementGuid>01735023-9988-4c5c-afb6-d810da7f5600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>51070af1-72f3-4f64-956f-892b2d5984e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>27008a4a-5ee0-4bb9-a78a-e8bb7cc90b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>fca518d0-a064-4207-869b-0b8b5277ca1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ff5c419c-7348-4a4c-9a96-2dc886ea98b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onManageLoan){onManageLoan(this,event);}</value>
      <webElementGuid>f2147bd6-a86b-484c-b037-0136305b451d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle  </value>
      <webElementGuid>f5ce31b5-6cd0-404d-903d-29b76b189823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal</value>
      <webElementGuid>942128dd-8dee-4427-8dea-d23747157981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stagename&quot;)</value>
      <webElementGuid>5797503e-db5e-422f-b171-9f6c924f1209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='stagename']</value>
      <webElementGuid>3517fc74-6a10-4251-ab58-eb8a95879333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tablepage']/div/div/div[3]/div/div/div/div/select</value>
      <webElementGuid>29a5810e-015b-4c75-8aec-8d9d807c6cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of all auto loan application'])[1]/following::select[1]</value>
      <webElementGuid>55c660cf-9bb2-4cbb-bd06-558231e2e469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[2]/following::select[1]</value>
      <webElementGuid>ef132154-8e16-4ff3-872b-0ff909b12403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show :'])[1]/preceding::select[1]</value>
      <webElementGuid>8e0a50d4-26d6-4f26-a912-2797e9ac038f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[4]/preceding::select[1]</value>
      <webElementGuid>8a76f8a3-559d-423a-9c6b-44d1dc7fe775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/select</value>
      <webElementGuid>57701cef-3fff-4be6-b8c8-378d448c5171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'All Application' and @id = 'stagename' and @name = 'stagename' and (text() = 'All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal' or . = 'All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal')]</value>
      <webElementGuid>c26d775e-9da0-4d18-8902-4479ab880f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
