<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>f04137f9-f671-48f8-95f3-470d15ab80c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button573']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button573</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1c5d0ec-0090-4953-9f64-4ea90c59379a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button573</value>
      <webElementGuid>0e6551dc-5f7a-49e2-bbca-f4212f810ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button573</value>
      <webElementGuid>f7014545-ab8f-44f7-ad87-42ee7a6abc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c989b58c-60d1-4c31-acbf-5aceebc94ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer </value>
      <webElementGuid>6923f120-436f-457a-9968-e52b0f017e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onSubmitClick){onSubmitClick(this,event);}</value>
      <webElementGuid>4294aa8f-c954-423e-abd8-70ab8e917f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Submit</value>
      <webElementGuid>6f47c123-db8e-4baf-88d7-ed854e4a8dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button573&quot;)</value>
      <webElementGuid>428f1edd-fde8-4389-ac75-50a134789b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DisbursementInfoNew/DisbursementInfoAndSubmit/iframe_Form_ngformIframe</value>
      <webElementGuid>990cc784-c0c2-44e5-b159-6b2728fa40fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button573']</value>
      <webElementGuid>746a18ce-3895-4dfd-848c-a73248e58ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='F_Decision']/div[2]/div/div[8]/div/button</value>
      <webElementGuid>e6355dfd-fb40-417d-a9b0-713fb3e0c84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid pattern !'])[1]/following::button[1]</value>
      <webElementGuid>aa79595f-f5b8-412e-8b82-cb2837cb2a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[351]/following::button[1]</value>
      <webElementGuid>7a6f116d-5ab9-4c9a-8e44-7d8a09e18411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receiving Date'])[1]/preceding::button[5]</value>
      <webElementGuid>2f3f0367-d452-4f05-8b0c-bdc5f4347776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Stage Name'])[1]/preceding::button[5]</value>
      <webElementGuid>58f65c3b-4347-4c80-9745-9f58ea58fad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/button</value>
      <webElementGuid>e31cd849-a3d2-4cda-85ba-9d8c9c489d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button573' and @name = 'button573' and @type = 'button' and (text() = ' Submit' or . = ' Submit')]</value>
      <webElementGuid>2065c592-c917-4a62-a5f2-f135371cbf4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
