<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>decision</name>
   <tag></tag>
   <elementGuidId>8ee10dcc-237d-42d5-b66f-93933a8a954d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Decision_Remarks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Decision_Remarks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d8015842-c964-4b5a-a6ad-7fb037947a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>3c0a3b04-504f-436a-8d60-d2e25a124583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad09b1a8-3513-48aa-b3dd-58caf4065273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ca59a54e-f6d8-42e0-88b9-791f2f038798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>63f3c8ff-24c8-4ef0-adca-e52c55df687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>de6c31b0-473e-4e6d-9be5-05834788607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Decision_Remarks</value>
      <webElementGuid>5157881a-2cd6-49d2-9654-852f0e10a3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Decision_Remarks</value>
      <webElementGuid>d172ed48-d47a-4a6f-8701-03b92865bc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>90630d3c-2f5e-4a2d-85e6-ba8be35db048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','Decision_Remarks')){return false;}if(event.keyCode==114){event.preventDefault();}</value>
      <webElementGuid>20340526-2a69-4ea2-85fc-f3b3d39399c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>6e9184d6-8e0a-4911-b577-46fea949370c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e6e21588-80af-42c9-8de7-e7b25053a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>    form-textarea form-input control-class inputStyle </value>
      <webElementGuid>8f1f1053-e3fc-4252-82e2-0e9193a9b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Decision_Remarks&quot;)</value>
      <webElementGuid>9cb25c91-0bf0-42df-a468-259ad6e212c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DisbursementInfoNew/DisbursementInfoAndSubmit/iframe_Form_ngformIframe</value>
      <webElementGuid>f7626efd-40be-46e3-9d58-fedd91380d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Decision_Remarks']</value>
      <webElementGuid>af2da465-ee4f-405a-9b34-dd7d63e08073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='F_Decision']/div[2]/div/div[7]/div/div/div/textarea</value>
      <webElementGuid>102c3674-113d-43b7-b477-c594d9a978ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>9f74bfec-1b2e-409a-a347-4a0fdcab113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'textarea' and @id = 'Decision_Remarks' and @name = 'Decision_Remarks']</value>
      <webElementGuid>0c1bcf85-0422-4cc2-94da-5d442878c10f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
