<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modeOfDisbursement</name>
   <tag></tag>
   <elementGuidId>a1bbbc6b-d6fa-4e84-9099-4bfd46b373c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QNL_AgentsCommission_Mode_of_Disbursement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#QNL_AgentsCommission_Mode_of_Disbursement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ec703aaa-fabe-4469-8be8-93cb1d3b7a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle advancedListviewControl</value>
      <webElementGuid>8b784192-9ecd-444b-bb6e-b466f8744354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>c156580a-c723-48f0-a37b-8996aa619ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QNL_AgentsCommission.Mode_of_Disbursement</value>
      <webElementGuid>4513f015-568d-4dea-8100-0519e8077d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9a8657af-b1af-41e8-88d9-cc54a43868e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Mode_of_Disbursement</value>
      <webElementGuid>109c9eda-a8e5-4be4-b71c-85c3e457b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Mode_of_Disbursement</value>
      <webElementGuid>524bce2d-b897-402c-b5b4-f4fd7911db07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Mode_of_Disbursement</value>
      <webElementGuid>490f4a6b-957a-43c8-8588-d4272fc78040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>c4e9b2c2-0b33-4136-96ca-7b237ae0c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectCredit to RCBC CASA</value>
      <webElementGuid>45d0d791-69de-4508-9757-cfbc9572aeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QNL_AgentsCommission_Mode_of_Disbursement&quot;)</value>
      <webElementGuid>0836aeeb-3772-4fd3-960f-1004aa174c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DisbursementInfoNew/DisbursementInfoAndSubmit/iframe_Form_ngformIframe</value>
      <webElementGuid>8e5cb178-9fc1-4d4c-b2a4-fd00dcb6da3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QNL_AgentsCommission_Mode_of_Disbursement']</value>
      <webElementGuid>2eff9380-7705-415e-a38c-73d6df1037fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table722_frame818']/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>f61ecae6-6a56-4412-a9b8-af81d1da1ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[558]/following::select[1]</value>
      <webElementGuid>89f7b5f6-7afb-4269-b1e1-a00ba07e28da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payee Name'])[3]/following::select[1]</value>
      <webElementGuid>245e1121-3780-495a-a725-2f24ac20f73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode of Disbursement'])[4]/preceding::select[1]</value>
      <webElementGuid>2e7ad40c-963e-4581-bf50-a768213cccac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[559]/preceding::select[1]</value>
      <webElementGuid>b68b61e0-f34e-4595-8497-c9794eac0dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>da79b2b4-9f01-4e23-b2c4-2ffb6d60310a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'QNL_AgentsCommission_Mode_of_Disbursement' and @id = 'QNL_AgentsCommission_Mode_of_Disbursement' and (text() = 'SelectCredit to RCBC CASA' or . = 'SelectCredit to RCBC CASA')]</value>
      <webElementGuid>6336989a-9511-4175-8569-a08690bfd85b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
