<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payeeName</name>
   <tag></tag>
   <elementGuidId>97dcf930-a55f-4c97-8c66-18001189ce51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QNL_AgentsCommission_Payee_Name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#QNL_AgentsCommission_Payee_Name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c86fc435-8fac-491c-8943-843c87ae935d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle advancedListviewControl</value>
      <webElementGuid>6e49a8f1-133c-44a7-a57e-d4e29525f409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);executeDBLinking(event,'QNL_AgentsCommission_Payee_Name','%5B%7B%22controls%22:%22QNL_AgentsCommission_Mode_of_Disbursement%22%2C%22index%22:0%2C%22event%22:%22Change%22%7D%2C%7B%22controls%22:%22QNL_AgentsCommission_Account_No%22%2C%22index%22:1%2C%22event%22:%22Change%22%7D%2C%7B%22controls%22:%22QNL_AgentsCommission_Bank_Name%22%2C%22index%22:2%2C%22event%22:%22Change%22%7D%2C%7B%22controls%22:%22QNL_AgentsCommission_TaxRate%22%2C%22index%22:3%2C%22event%22:%22Change%22%7D%5D');</value>
      <webElementGuid>221a28f7-a792-4898-adab-5481c340a122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QNL_AgentsCommission.Payee_Name</value>
      <webElementGuid>d91fdbb6-30cf-4653-87cc-bda117209137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>dade7942-010f-4857-b331-90f9b9036a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Payee_Name</value>
      <webElementGuid>ec8df287-f9ee-43b6-a260-37b5f1100bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Payee_Name</value>
      <webElementGuid>d652a9ce-23bb-49ab-8343-deb31e6534ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QNL_AgentsCommission_Payee_Name</value>
      <webElementGuid>3fdd1143-9b80-4d50-b63a-f8b5f5ef2b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>e17faa08-d6d5-478d-9299-08699d6d6e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectGLIZEL M. MILLENA</value>
      <webElementGuid>0addecea-99ae-4e33-9032-45541cec38ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QNL_AgentsCommission_Payee_Name&quot;)</value>
      <webElementGuid>259d9fb2-80e3-4efe-93ee-912d23ba9f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DisbursementInfoNew/DisbursementInfoAndSubmit/iframe_Form_ngformIframe</value>
      <webElementGuid>b82aa83f-1782-4e87-ba62-f8b8f763ff75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QNL_AgentsCommission_Payee_Name']</value>
      <webElementGuid>0d98be23-1490-41a2-bd43-15d4e25d4f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table722_frame818']/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>7fa43f9b-dce7-4053-82bd-1ebc0378d32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disbursement for DI'])[1]/following::select[1]</value>
      <webElementGuid>c05349f7-6f93-46d6-9e1e-0a4d22e6d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Close'])[1]/following::select[1]</value>
      <webElementGuid>17c636bc-b6cd-4004-8d4c-5a3b03528fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payee Name'])[3]/preceding::select[1]</value>
      <webElementGuid>40d21669-1043-4c77-a75b-1d5ea0b801dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[558]/preceding::select[1]</value>
      <webElementGuid>c9dd125b-913b-413e-8e66-ade82ad86e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>5ae939fa-88e6-4399-8420-8b2dfd7398a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'QNL_AgentsCommission_Payee_Name' and @id = 'QNL_AgentsCommission_Payee_Name' and (text() = 'SelectGLIZEL M. MILLENA' or . = 'SelectGLIZEL M. MILLENA')]</value>
      <webElementGuid>0ddccf71-162e-41fb-be12-ff8c69f92e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
