<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveAndClose</name>
   <tag></tag>
   <elementGuidId>5d644b7f-a336-4c80-96dd-be0353148a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addAdvancedListviewrow_Keymans_commision']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addAdvancedListviewrow_Keymans_commision</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2690a49b-7a5c-4cb9-8435-dd1ef23e68d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>a1a43b7c-2d22-4f1e-9170-5feed576b206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addAdvancedListviewrow_Keymans_commision</value>
      <webElementGuid>af06af82-13ca-430d-9759-c2e3d97aad03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addRowToAdvancedListview('Keymans_commision');</value>
      <webElementGuid>95e8cd6b-5715-40e2-baed-e6452fa68879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e1aa5ea-96bf-4775-885e-b10d5472a156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save and Close</value>
      <webElementGuid>f44d7069-d12c-43cb-a052-2c7fb441549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addAdvancedListviewrow_Keymans_commision&quot;)</value>
      <webElementGuid>99a916f4-0251-4575-8efa-9617b472d85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DisbursementInfoNew/DisbursementInfoAndSubmit/iframe_Form_ngformIframe</value>
      <webElementGuid>6159bd1f-27e5-4a6c-920d-b1c9ac055d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addAdvancedListviewrow_Keymans_commision']</value>
      <webElementGuid>cb460e7f-f27f-4eb3-8e8f-8be6b9a20bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedListViewModalContent']/div/div/span[2]/div[2]/button</value>
      <webElementGuid>c74bfd66-52dc-49c1-a78a-481a849f22f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Next'])[1]/following::button[1]</value>
      <webElementGuid>5185e9d4-7c0a-46be-8b69-b38ae0f42667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[4]</value>
      <webElementGuid>64403043-c9c1-4897-b10c-5513ea436a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disbursement for DI'])[1]/preceding::button[2]</value>
      <webElementGuid>84775ae2-bb99-4e4c-a24a-09b2a08ab661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payee Name'])[3]/preceding::button[2]</value>
      <webElementGuid>d5b7b5ea-c609-401e-a676-a5549f66a8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and Close']/parent::*</value>
      <webElementGuid>292dca67-b762-4037-a7ee-b15a0f11c4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[2]/button</value>
      <webElementGuid>74b7e3dc-7629-4146-8d27-24a8bbd2e1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addAdvancedListviewrow_Keymans_commision' and @type = 'button' and (text() = 'Save and Close' or . = 'Save and Close')]</value>
      <webElementGuid>7a3ea931-72c1-49ed-8825-9a7e9b29b11a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
