<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Actual_Unit_Release_Date</name>
   <tag></tag>
   <elementGuidId>1556907e-d3bc-4032-9339-6acd8f8e72e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Actual_Unit_Release_Date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_LoanInformation_Actual_Unit_Release_Date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84524fa9-8c61-4dec-b462-29e210c3a17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>00/00/0000</value>
      <webElementGuid>5a085ec6-f216-46af-8341-9a62b17651c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Actual_Unit_Release_Date</value>
      <webElementGuid>1adb75fa-449d-4a78-98a1-dc1d984b8f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>bcd916ca-eb21-487a-944b-f04efa2363df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d499039-6715-4f55-a21e-31f2323587be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Actual_Unit_Release_Date</value>
      <webElementGuid>8a34a5a0-e544-4563-8299-a64ecb6bf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Actual_Unit_Release_Date</value>
      <webElementGuid>4dac45e5-e54d-4ccb-ba4f-a70b08582e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Actual_Unit_Release_Date</value>
      <webElementGuid>867c8342-6920-4541-8c8c-8ebaa4725e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2425864c-1cbd-42be-94ee-44b723194a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ab6705a8-b644-47fb-8aff-d2a278757f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-input mydatepicker inputStyle input-focus</value>
      <webElementGuid>ed40cd52-c79b-465c-930c-3b550e22ce90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dateformat</name>
      <type>Main</type>
      <value>1_1_1</value>
      <webElementGuid>8e654bb9-20a2-420f-8fa4-27aeb3aad523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>7c2b0f75-df34-4cd3-b101-3b5515b9b22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mindate</name>
      <type>Main</type>
      <value>17/05/2024</value>
      <webElementGuid>c9998bdf-5cf5-4a10-ad02-4ef12e800658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>modifyClass(this); attachDateRange(this);</value>
      <webElementGuid>cbd3027d-806a-4cfd-a1f2-b3a0ad2dd615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>22/05/2024</value>
      <webElementGuid>3565b429-7906-4444-9bba-c1889309b6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Actual_Unit_Release_Date&quot;)</value>
      <webElementGuid>3e2aacd3-6e3e-4dc7-8b1b-fd3ad5c8beec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>775a4ec7-2c32-4223-a4bd-018c9a2174f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_LoanInformation_Actual_Unit_Release_Date']</value>
      <webElementGuid>e1f3f71c-4816-4bbe-947a-098b1193c36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[35]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>2c10ce70-7a19-4de5-99bf-8bd0e3474917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>bbba4761-edfa-489d-988c-97bbd8b14fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_LoanInformation_Actual_Unit_Release_Date' and @name = 'QL_LoanInformation_Actual_Unit_Release_Date' and @type = 'text' and @title = '22/05/2024']</value>
      <webElementGuid>b7b3ff22-86ce-4604-9487-a2a66983182b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
