<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>felxiliteRatio</name>
   <tag></tag>
   <elementGuidId>6b5d5b15-0092-490c-9a0a-b2263554193a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Flexitate_Ratio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_LoanInformation_Flexitate_Ratio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08559757-3c9c-42fe-b82f-8f9ed797b4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>484d390e-6cd8-4ad0-8cd0-90ee05fcae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Flexitate_Ratio</value>
      <webElementGuid>0db2b63b-3b85-4e18-9ea8-2d5e7a6df6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Flexitate_Ratio</value>
      <webElementGuid>1809959e-8a36-4190-95e3-916926e61834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Flexitate_Ratio</value>
      <webElementGuid>b06ae770-1ca9-491c-bd60-a4e44b595ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>869e5608-b640-43a5-8021-cdb41bba4707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>1f059e77-cb0c-4cb5-8778-4f9472f9d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Flexitate_Ratio</value>
      <webElementGuid>5f72771a-51ed-4ac9-aa42-aebf8f5a1dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onchangeflexi){onchangeflexi(this,event);}</value>
      <webElementGuid>7c6472b2-b13d-4f14-822c-9d9a1107f20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>96c3c19d-3c9e-48ea-b4de-3a29dacc211c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select30%40%</value>
      <webElementGuid>0ea36c6b-fd11-4f6a-86c3-4020ade36094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Flexitate_Ratio&quot;)</value>
      <webElementGuid>bfce0238-5778-47bd-bd1a-e78aa648f79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>eb6ea9ea-2275-4b2c-a38d-e8bff16ea666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_LoanInformation_Flexitate_Ratio']</value>
      <webElementGuid>ba504af5-cb0c-4b37-94ba-0c3175bb2088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[11]/div/div/div/select</value>
      <webElementGuid>3537bc50-0c14-4360-a195-00526456e378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[83]/following::select[1]</value>
      <webElementGuid>2fbee235-9be3-4bdc-9253-224c0280e4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexilite Indicator'])[1]/following::select[1]</value>
      <webElementGuid>bbd2ffba-45b1-4586-9447-5fa0411d4151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flexilite Ratio'])[1]/preceding::select[1]</value>
      <webElementGuid>be828958-74ce-4e4e-b1b7-e15ef59c5906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[84]/preceding::select[1]</value>
      <webElementGuid>be1ae88c-a4c0-4872-9d01-bbe1503a0a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[11]/div/div/div/select</value>
      <webElementGuid>cf24fd0e-c142-4bc4-ae1d-ac94b44087d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'QL_LoanInformation_Flexitate_Ratio' and @name = 'QL_LoanInformation_Flexitate_Ratio' and (text() = 'Select30%40%' or . = 'Select30%40%')]</value>
      <webElementGuid>080157e5-4f93-47eb-8c5e-b514b42e064e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
