<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>2ebe381f-6a5d-4d7a-9d88-3a9c0b3b7e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ngformIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7f32f911-8006-47be-983e-ee3ac5f687e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>f696f187-032c-4a70-86d4-808c78b9f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000433&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000433&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=3b5f556c-3675-4d3d-91f7-1a04d203d4c8&amp;WD_RID=dbedfcb0-3a76-4912-8c72-a5a3bc13b421&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=a1c1bf1d-f2dc-456f-bca6-f594a9c7ccd2&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>9012f7b4-c9a3-4401-b898-85dde04f9d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>93299e89-780e-4f71-8cf4-38e56fcecb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>909e5f06-884a-45b8-b1d7-c1d65b62befb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7df9205-0292-42c1-aef9-38aa7bf23da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce7ceede-3173-4da3-9b38-5e7264d9421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>30bf8897-7efa-4da0-ae5d-436a0de107d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>019c22c4-f737-4395-a703-57c8a059a81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>e5736b0f-baa5-4d72-90f1-034dc380718d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>58ac0d7b-e8b8-405c-8225-7a519a3462fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000433&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000433&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=3b5f556c-3675-4d3d-91f7-1a04d203d4c8&amp;WD_RID=dbedfcb0-3a76-4912-8c72-a5a3bc13b421&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=a1c1bf1d-f2dc-456f-bca6-f594a9c7ccd2&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>f121ec17-9097-451d-a17d-0280257a5e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
