<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>insuranceType</name>
   <tag></tag>
   <elementGuidId>ec562b19-1fc5-4d72-8116-54f2f91ed0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Insurance_Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_LoanInformation_Insurance_Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>46852074-b524-45ef-9336-5709f5e3fe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>18ada271-8eac-42cf-bce6-0782b45560dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Insurance_Type</value>
      <webElementGuid>d2d45b9e-dc2d-47f7-91fc-bbdcbcb41e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Insurance_Type</value>
      <webElementGuid>2392661b-ee45-41aa-996d-4ff566c8442e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Insurance_Type</value>
      <webElementGuid>eaca337c-0816-4082-97b1-e3681c9b140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>c5071af4-8eef-46e4-b102-065044e51fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a865001d-aa8f-4971-9c58-4be740234a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Insurance_Type</value>
      <webElementGuid>8408c6cd-97ef-4142-b600-2286435ff447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onchangeinsuranceBO){onchangeinsuranceBO(this,event);}</value>
      <webElementGuid>c015c0bf-82ff-4b53-aeda-63eb7adb2e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>934e0c4f-01b1-4095-b76e-56fb4be41cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAuto Loan Plus DeferredAuto Loan Plus (ALP)EndorsedFree Insurance Promo (FIP)RegularTucked-in FIP DeferredTucked-in FIPTucked-in Regular</value>
      <webElementGuid>862f364d-0ded-4448-b637-57133bc370ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Insurance_Type&quot;)</value>
      <webElementGuid>7f9b5e11-13f7-450b-9117-1a265b823e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>d8fa291c-70f4-4c33-91ac-79960c359d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_LoanInformation_Insurance_Type']</value>
      <webElementGuid>99c785bf-b30b-4fab-88ae-de2fd639b3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[22]/div/div/div/select</value>
      <webElementGuid>4449222c-aad8-4e95-9138-7918ccd6541f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[94]/following::select[1]</value>
      <webElementGuid>8203962f-3cb7-4ef6-8cd3-ec959a3b5da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[10]/following::select[1]</value>
      <webElementGuid>397cc8f2-7156-4c93-8b10-2fc8fc778c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insurance Type'])[1]/preceding::select[1]</value>
      <webElementGuid>ad42f889-c507-46fe-8860-a6f90ac7e01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[95]/preceding::select[1]</value>
      <webElementGuid>307e15fd-313a-420f-b703-663965bcb2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/div/select</value>
      <webElementGuid>c37cdd33-231c-4682-afc6-ee789d708cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'QL_LoanInformation_Insurance_Type' and @name = 'QL_LoanInformation_Insurance_Type' and (text() = 'SelectAuto Loan Plus DeferredAuto Loan Plus (ALP)EndorsedFree Insurance Promo (FIP)RegularTucked-in FIP DeferredTucked-in FIPTucked-in Regular' or . = 'SelectAuto Loan Plus DeferredAuto Loan Plus (ALP)EndorsedFree Insurance Promo (FIP)RegularTucked-in FIP DeferredTucked-in FIPTucked-in Regular')]</value>
      <webElementGuid>07f1b1b1-bb48-4b11-a956-37c49dda5890</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
