<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loanPurpose</name>
   <tag></tag>
   <elementGuidId>c6438a8e-16d6-4c85-842f-988cd415271d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Loan_Purpose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_LoanInformation_Loan_Purpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1fe40d8a-c043-4eb8-b98a-cf04efff59c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>773d51e3-6ae0-474c-ae1f-fa5427295cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Loan_Purpose</value>
      <webElementGuid>c207f1dc-2753-4ce6-89a7-d6503cd1eb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Auto Loan Acquisition - Brand new</value>
      <webElementGuid>2392fcb2-09d7-4707-bd5d-3d81077995f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Loan_Purpose</value>
      <webElementGuid>b908af6f-ff22-46d4-a0c2-09b10af57fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Loan_Purpose</value>
      <webElementGuid>a2ffceb6-14b2-423f-8736-e95827df6f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>63f05ee9-b4be-45fa-87e2-fb3850a954a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7c756521-05f8-4f2d-ac40-aa9555073b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Loan_Purpose</value>
      <webElementGuid>a014511f-6755-4b86-9d30-7c37e3059437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>ddd07960-998c-4858-bac1-a855de7602b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>217c6291-433c-452d-89be-be41d5645c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAuto Loan Acquisition - Brand newAuto Loan RefinancingAuto Loan Acquisition - Used Car</value>
      <webElementGuid>59390c9b-ba68-4d34-a2b1-cdba306f1baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Loan_Purpose&quot;)</value>
      <webElementGuid>e01cf693-bd9a-4f46-a1cb-e9525d6036a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>9c09c927-cd78-429f-afc7-69e25833522b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_LoanInformation_Loan_Purpose']</value>
      <webElementGuid>461bbdbe-ac25-4ef2-9f62-d2e401576d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[27]/div/div/div/select</value>
      <webElementGuid>19953a73-d7f4-4908-8d02-2cc30c78e159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Approval'])[1]/following::select[1]</value>
      <webElementGuid>a3c1b29d-bf9b-4e63-9ba7-99ebb5ccc8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[97]/following::select[1]</value>
      <webElementGuid>ef35f623-b8ee-4cc7-89c6-f2517218ab7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Purpose'])[1]/preceding::select[1]</value>
      <webElementGuid>56a899da-e764-4b94-adb6-7bb288e70760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[98]/preceding::select[1]</value>
      <webElementGuid>e1537134-a3f3-42a1-89a0-911248494e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div/div/select</value>
      <webElementGuid>5a3e82d1-b550-4bc0-bfc6-b65d78069246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Auto Loan Acquisition - Brand new' and @id = 'QL_LoanInformation_Loan_Purpose' and @name = 'QL_LoanInformation_Loan_Purpose' and (text() = 'SelectAuto Loan Acquisition - Brand newAuto Loan RefinancingAuto Loan Acquisition - Used Car' or . = 'SelectAuto Loan Acquisition - Brand newAuto Loan RefinancingAuto Loan Acquisition - Used Car')]</value>
      <webElementGuid>3c7d09e4-9bcf-4d47-85f5-c8d33cd0d201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
