<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>marketingPromoCode</name>
   <tag></tag>
   <elementGuidId>a9359710-ae06-429a-83cc-0d11ab2747b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Marketing_Promo_Code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_LoanInformation_Marketing_Promo_Code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b68ef800-8d35-499e-bf81-3b83bc728082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>936696c3-60d4-42cb-8b8b-11a16771650f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Marketing_Promo_Code</value>
      <webElementGuid>e5286b12-c16a-429e-a48a-7676656c640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MMPC's Free 1 month Amortization Promo on the Xpander</value>
      <webElementGuid>cb61e8f7-b1e3-4e68-b051-9517c68a83eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Marketing_Promo_Code</value>
      <webElementGuid>a7062919-07c8-4c01-ae89-a8cff45f67aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Marketing_Promo_Code</value>
      <webElementGuid>4fcf6bb5-9fc4-486c-a233-51d027217013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>4e075d3a-2b57-43c1-9091-0f97672a9413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>1960376c-e6f4-4e99-aa90-f438603a025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Marketing_Promo_Code</value>
      <webElementGuid>e94d260c-9121-4d27-be5c-c9a4d6baf9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>fe6c478b-0ab3-48ff-ad8a-4a50820d7ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>1ad581bb-9149-4a8c-9110-a5ddab939132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectMMPC's Free 1 month Amortization Promo on the XpanderMMPC's Free Amortization Promo for the Montero SportMMPC's Free 2 months Amortization Promo for the L300Mistubishi's Free 2 months Amortization Promo on the Mirage G4Mistubishi's P40k Subsidy Promo on the Mirage G4</value>
      <webElementGuid>b2ae0404-c982-4b4d-ba6c-44d8134c0633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Marketing_Promo_Code&quot;)</value>
      <webElementGuid>3c739089-9dcc-45eb-9b3b-87f4f72b71e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>ed79b8d9-9b42-4a45-8b4b-083186e28a40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_LoanInformation_Marketing_Promo_Code']</value>
      <webElementGuid>f1936858-a35c-4dbf-b4f1-7186f86d9e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[4]/div/div/div/select</value>
      <webElementGuid>7f696abe-343d-45b0-8889-48bd1250844c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[77]/following::select[1]</value>
      <webElementGuid>2850719e-07ef-41b1-826d-eb349df668f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Type'])[2]/following::select[1]</value>
      <webElementGuid>fe4d80e8-4bb1-4775-9627-dc45e3ed65c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing Promo Code'])[2]/preceding::select[1]</value>
      <webElementGuid>916d7ff4-c587-4f27-99b9-82a4802850ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[78]/preceding::select[1]</value>
      <webElementGuid>8adca73d-1706-43e9-820c-2c33cc948754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[4]/div/div/div/select</value>
      <webElementGuid>6c4c67d4-f02e-4536-a787-46f05ac46ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = concat(&quot;MMPC&quot; , &quot;'&quot; , &quot;s Free 1 month Amortization Promo on the Xpander&quot;) and @id = 'QL_LoanInformation_Marketing_Promo_Code' and @name = 'QL_LoanInformation_Marketing_Promo_Code' and (text() = concat(&quot;SelectMMPC&quot; , &quot;'&quot; , &quot;s Free 1 month Amortization Promo on the XpanderMMPC&quot; , &quot;'&quot; , &quot;s Free Amortization Promo for the Montero SportMMPC&quot; , &quot;'&quot; , &quot;s Free 2 months Amortization Promo for the L300Mistubishi&quot; , &quot;'&quot; , &quot;s Free 2 months Amortization Promo on the Mirage G4Mistubishi&quot; , &quot;'&quot; , &quot;s P40k Subsidy Promo on the Mirage G4&quot;) or . = concat(&quot;SelectMMPC&quot; , &quot;'&quot; , &quot;s Free 1 month Amortization Promo on the XpanderMMPC&quot; , &quot;'&quot; , &quot;s Free Amortization Promo for the Montero SportMMPC&quot; , &quot;'&quot; , &quot;s Free 2 months Amortization Promo for the L300Mistubishi&quot; , &quot;'&quot; , &quot;s Free 2 months Amortization Promo on the Mirage G4Mistubishi&quot; , &quot;'&quot; , &quot;s P40k Subsidy Promo on the Mirage G4&quot;))]</value>
      <webElementGuid>c8b17e08-509a-4f72-a295-b6a939b2452b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
