<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mode_Of_Payment</name>
   <tag></tag>
   <elementGuidId>d2906a84-6425-42aa-9cf4-a0efd07672a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_ModeOfPaymentData_Mode_of_Payment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_ModeOfPaymentData_Mode_of_Payment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f8b62787-6561-4e6d-990d-fbe2f187c54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>bbb7caa8-7694-42b9-ab90-2245a0dff0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_ModeOfPaymentData_Mode_of_Payment</value>
      <webElementGuid>eff8ffae-cdce-48ff-8434-97be883e7cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Over the Counter (OTC)</value>
      <webElementGuid>52dd5862-fed7-4975-a108-cb8f0afa5a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_ModeOfPaymentData_Mode_of_Payment</value>
      <webElementGuid>6c1198d8-0959-4c66-b25b-e6176831f9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_ModeOfPaymentData_Mode_of_Payment</value>
      <webElementGuid>5d334c4a-d1d7-4db1-b6b7-88e5aa331fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>70daa8ca-f5b3-48d3-8676-8fec58a2353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>06552bab-eb07-408a-9c7e-850b08dc52e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_ModeOfPaymentData.Mode_of_Payment</value>
      <webElementGuid>0cb30626-5dd3-4e29-b106-57f5d238d20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onChangeModeofPayment){onChangeModeofPayment(this,event);}</value>
      <webElementGuid>ad6d3cb4-6def-4e5d-8220-0e14eee95afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>4ebcce13-8691-4c86-9c53-f37be212c050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAuto Debit Arrangement (ADA)Over the Counter (OTC)Post-dated check (PDC)</value>
      <webElementGuid>3c3994f8-01e8-4182-ad66-d3143c079f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_ModeOfPaymentData_Mode_of_Payment&quot;)</value>
      <webElementGuid>15633616-52d2-46c9-a668-cb2e78a81787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>ce753ed2-d66c-4ed7-b7f4-72d7b7057107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_ModeOfPaymentData_Mode_of_Payment']</value>
      <webElementGuid>1e931727-9d9d-4262-86c2-27e3aeca0a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame763']/div[2]/div/div[2]/div/div/div/div/select</value>
      <webElementGuid>5b0772cb-4210-4200-822b-b5db927e12a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode of Payment'])[1]/following::select[1]</value>
      <webElementGuid>b7d1d252-8edc-42e4-94b9-60441ca859d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[139]/following::select[1]</value>
      <webElementGuid>e41d73b5-f204-4cb3-b420-df33612da527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mode of Payment'])[2]/preceding::select[1]</value>
      <webElementGuid>69ecff39-b478-461e-8ea5-ee6eef85e70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[140]/preceding::select[1]</value>
      <webElementGuid>3540ac82-aa12-44b2-8ff7-810213aad1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>6c56c34a-3e5f-4b23-92b6-6e464a879540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Over the Counter (OTC)' and @id = 'QL_ModeOfPaymentData_Mode_of_Payment' and @name = 'QL_ModeOfPaymentData_Mode_of_Payment' and (text() = 'SelectAuto Debit Arrangement (ADA)Over the Counter (OTC)Post-dated check (PDC)' or . = 'SelectAuto Debit Arrangement (ADA)Over the Counter (OTC)Post-dated check (PDC)')]</value>
      <webElementGuid>8e5b3e84-9387-4a5e-9faf-d7abf2bf612a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
