<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Payment_Type</name>
   <tag></tag>
   <elementGuidId>856082d7-ff51-458f-80cf-b8ad63de02d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_Promissory_Note_Information_Payment_Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_Promissory_Note_Information_Payment_Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a186d82-81d8-46c3-92ef-8119eea64e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>1c534105-a50c-43a8-8a0d-d1b3c0b9aa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Payment_Type</value>
      <webElementGuid>1a4f3458-c0a7-43e1-8964-1f4ae953889d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Principal Only</value>
      <webElementGuid>8b866ba0-adfa-4f4d-82b3-6995fdcb2eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Payment_Type</value>
      <webElementGuid>7cac53b2-523a-43dc-9919-1474bc01656d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Payment_Type</value>
      <webElementGuid>e3780cb9-be09-4497-a33b-57833f68ca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>2f968462-57b6-43d2-a7bd-5b2ab8864289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>acb7c122-1015-4ac3-b14e-9388227cf01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information.Payment_Type</value>
      <webElementGuid>2bd7f306-c432-4634-bda3-fb3dd3e43219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>6fcabb01-e1c5-455c-bb54-d7e154e77130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>abd99b10-5bdf-42d8-a8ac-b7332a7b79ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPrincipal OnlyEqual Monthly AmortizationEqual Principal Amortization (Interest Rate)Interest Only</value>
      <webElementGuid>ba75dbaa-07fd-49b9-a0c8-70a9f362bee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_Promissory_Note_Information_Payment_Type&quot;)</value>
      <webElementGuid>5ffc40c0-7010-434e-ba8c-4816782c55a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>47da27da-85c5-49d9-9c3e-91aacd27c488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_Promissory_Note_Information_Payment_Type']</value>
      <webElementGuid>4eac05df-b358-48bc-b2c6-ca81a3489556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame761']/div[2]/div/div[40]/div/div/div/select</value>
      <webElementGuid>99508a5c-0b33-418a-b4d6-0e7ac459de26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amortization Payment Schedule'])[1]/following::select[1]</value>
      <webElementGuid>4223f3f8-b79b-46c2-bbb0-c602f0af7df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[131]/following::select[1]</value>
      <webElementGuid>61329fbf-26f2-4d5f-aabf-5703ed3a06e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Type'])[1]/preceding::select[1]</value>
      <webElementGuid>1d3c7d23-dc53-4dc6-a776-128448034186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[132]/preceding::select[1]</value>
      <webElementGuid>507d3373-ea3a-4e58-b778-a244ccc098e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[40]/div/div/div/select</value>
      <webElementGuid>1e0f351a-56ce-4e3d-8ac6-84e28df2fa86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Principal Only' and @id = 'QL_Promissory_Note_Information_Payment_Type' and @name = 'QL_Promissory_Note_Information_Payment_Type' and (text() = 'SelectPrincipal OnlyEqual Monthly AmortizationEqual Principal Amortization (Interest Rate)Interest Only' or . = 'SelectPrincipal OnlyEqual Monthly AmortizationEqual Principal Amortization (Interest Rate)Interest Only')]</value>
      <webElementGuid>f9e4305c-75db-4b5f-811a-365eab3a624f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
