<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Processing_Fee</name>
   <tag></tag>
   <elementGuidId>e7d538c6-897a-461a-9f94-04e7755ce81b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_Promissory_Note_Information_Processing_Fee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_Promissory_Note_Information_Processing_Fee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8263cb9f-3547-401f-95f8-5882c9d13e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>f58dcabf-5e1d-48fd-ac3a-d4f57b077655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f480e8ec-c0e4-458e-a52f-ead5a226c57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0894f2af-8801-43eb-a5c9-63a6763d1026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>b21db076-14fe-4fca-8043-c11bba5a55a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Processing_Fee</value>
      <webElementGuid>38649c9b-bc1a-4e14-acff-c440abc0e36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Processing_Fee</value>
      <webElementGuid>b2909495-3927-49ec-99ee-6d87b0d4612f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information.Processing_Fee</value>
      <webElementGuid>9dfde811-bd16-4cfe-b2bc-13af2e4212c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>01e90b3d-8e9f-4b14-a830-6dde89799f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Float</value>
      <webElementGuid>f63b938c-695b-4215-8734-cc2de7939351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>65e7d1d7-1e6e-437e-80a2-6d6266fc15fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>1388097c-ec8f-4916-aee0-a9aa57f92b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>6b61716d-414f-4d8d-9c84-0211556be68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QL_Promissory_Note_Information_Processing_Fee')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QL_Promissory_Note_Information_Processing_Fee');</value>
      <webElementGuid>1d45f121-3369-40ab-a4ab-623d27741110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>a7be1b42-767b-4b15-bdb8-4e366341fb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>477dfab6-5de5-406a-8ce0-e5787980070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>17a3ecd3-a9f1-411e-b295-bedbaaea6027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c1a650f-8189-4178-90c9-44dadcc4794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox</value>
      <webElementGuid>07e66e42-23e8-4ae4-af30-f419a43bf07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>91715bdf-f62d-4ad8-aca0-92a9c60ba935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_Promissory_Note_Information_Processing_Fee&quot;)</value>
      <webElementGuid>315a3aa8-d42d-4aca-83c6-5a4faeaa4e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>132e2b15-35ee-4230-ab7d-cf4fd4c6552d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_Promissory_Note_Information_Processing_Fee']</value>
      <webElementGuid>5b23b51d-19ac-4f4f-8d8b-1756a1a04b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame761']/div[2]/div/div[14]/div/div/div/input</value>
      <webElementGuid>940eb9e1-61e8-455c-8ba0-537c4e9f83ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[14]/div/div/div/input</value>
      <webElementGuid>172c98fc-261b-4930-8d7d-5d9ba2cbd73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_Promissory_Note_Information_Processing_Fee' and @name = 'QL_Promissory_Note_Information_Processing_Fee' and @type = 'text']</value>
      <webElementGuid>743170ff-8da9-4570-baf0-16525c366e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
