<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scheduled_Unit_Release_Date</name>
   <tag></tag>
   <elementGuidId>705be2fc-5521-4bfc-87d9-fc0bf1c987b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Scheduled_Unit_Release_Date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_LoanInformation_Scheduled_Unit_Release_Date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bf295e2-9eb8-49d1-ba0e-70f05e20c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>00/00/0000</value>
      <webElementGuid>6fd45b0c-2fa2-4225-969f-fefffa621e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Scheduled_Unit_Release_Date</value>
      <webElementGuid>6cbef8c2-0f03-40a2-8f39-4dc8f7689377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>5eecb0a7-a0bb-4f62-8b39-4bb314f58016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>83823150-a316-4658-be9e-5c939e4773a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Scheduled_Unit_Release_Date</value>
      <webElementGuid>c6587b9a-4414-4606-8139-9f48d5670ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Scheduled_Unit_Release_Date</value>
      <webElementGuid>ece8e0ec-df72-4cf6-ac8c-c801842e19cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Scheduled_Unit_Release_Date</value>
      <webElementGuid>4ec309e6-5d48-4e03-bf92-5b509c6358ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea691486-7d48-4b9e-8500-48be886d6ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4e85358d-473a-4420-9939-c04e6128a1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-input mydatepicker inputStyle input-focus</value>
      <webElementGuid>cc11f9c8-ab68-401e-8cf6-3e9088afaf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dateformat</name>
      <type>Main</type>
      <value>1_1_1</value>
      <webElementGuid>891f4a08-8e9c-4f52-b07e-f9dd701e7b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>format</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>b0f094b6-c101-4baa-9e9f-c39c673809da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mindate</name>
      <type>Main</type>
      <value>17/05/2024</value>
      <webElementGuid>02234f86-7d7d-434b-b9a3-7c4fae51e2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>modifyClass(this); attachDateRange(this);</value>
      <webElementGuid>f7c5b348-0fe8-4317-8a17-e058a3651d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>21/05/2024</value>
      <webElementGuid>2ba64d17-f33b-4d62-a691-9f781f6390e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Scheduled_Unit_Release_Date&quot;)</value>
      <webElementGuid>d9856a42-4220-4823-a8a5-1d164dd7cb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>931c629b-c967-42c6-bc7c-f03fd06dbae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_LoanInformation_Scheduled_Unit_Release_Date']</value>
      <webElementGuid>328adc0e-5339-49b3-9eba-67d6043a1f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[34]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>6766b20d-3e12-4614-b937-0cb0e59b4c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9e4e5226-f334-412d-80d0-53f909f973d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_LoanInformation_Scheduled_Unit_Release_Date' and @name = 'QL_LoanInformation_Scheduled_Unit_Release_Date' and @type = 'text' and @title = '21/05/2024']</value>
      <webElementGuid>51be4f53-a064-4e72-987a-8aaaaaf15632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
