<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Product_Type</name>
   <tag></tag>
   <elementGuidId>36179709-04d1-4bd8-b7bf-3983bb6f0eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_LoanInformation_Product_Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QL_LoanInformation_Product_Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>19b5e0aa-8440-4060-91a5-1d98504745c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>4c989bb3-9c35-4b86-883a-ea906f692871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QL_LoanInformation_Product_Type</value>
      <webElementGuid>f3b09509-80b4-4dde-940e-e452d545c6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_LoanInformation_Product_Type</value>
      <webElementGuid>33b25759-0398-4cba-ba8f-adaccaee9092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_LoanInformation_Product_Type</value>
      <webElementGuid>1a37120e-3e36-4221-a39d-e266b781b527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>1295c8ba-d4aa-4144-b623-bdda38a242d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>0b600643-1a92-424f-ad13-c92087a88e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_LoanInformation.Product_Type</value>
      <webElementGuid>0192d444-fa53-494a-9e8d-a26689865918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>17ad7558-c645-4823-a94e-54a411c2a8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>e6079e66-4906-4dfe-a0fd-9ea32e48d6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>c396658a-3cfb-4398-9d43-e06b1c172aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_LoanInformation_Product_Type&quot;)</value>
      <webElementGuid>61b53cef-d736-4e57-8644-f6619bc9836e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>34f9cc36-0db2-438b-97ce-315ea9180e7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QL_LoanInformation_Product_Type']</value>
      <webElementGuid>dfeec7d0-8baa-4b3a-9b1a-44a8ac84615c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame759']/div[2]/div/div[3]/div/div/div/select</value>
      <webElementGuid>4e77c0f3-8f7a-45c6-9a64-b3ce93d7fd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[76]/following::select[1]</value>
      <webElementGuid>10f0f067-4711-4386-aed5-771b1db51563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[29]/following::select[1]</value>
      <webElementGuid>f1849ce1-1381-49c7-b9aa-b5aa5595107e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Type'])[2]/preceding::select[1]</value>
      <webElementGuid>674790be-abfe-4290-8db7-2eac37ec3b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[77]/preceding::select[1]</value>
      <webElementGuid>a4170480-1ac7-4694-a0ce-278c91eea32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/select</value>
      <webElementGuid>a3b0b8eb-f8db-4575-98d2-170908f6e373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'QL_LoanInformation_Product_Type' and @name = 'QL_LoanInformation_Product_Type' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>6082af83-406a-4952-aa42-78bc6ddde1de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
