<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subsidy_special_co_dealer</name>
   <tag></tag>
   <elementGuidId>6aa2d027-2481-401f-bcee-ec8a12e162b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_Promissory_Note_Information_Subsidy_special_co_dealer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_Promissory_Note_Information_Subsidy_special_co_dealer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a405ff9d-daa3-4df4-b39f-39b0a02a2167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>7bf8e1af-92f0-4ea9-96b5-577fd80fb065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>91d03abe-2f54-4abe-9fe7-4b0bf91beefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af06ed01-9ff9-4286-8cd5-a2415a63c5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>0748a22c-a8cf-456c-9ac2-e68d988439df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Subsidy_special_co_dealer</value>
      <webElementGuid>311d9fc8-1c11-453f-83f2-3470b715430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Subsidy_special_co_dealer</value>
      <webElementGuid>aed06215-bffc-4f58-a0a3-97e516cb5624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information.Subsidy_special_co_dealer</value>
      <webElementGuid>20eccaa8-d0d9-4ea1-83f1-f443c734ab13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>75a0a011-8863-44af-a4dc-769367a4dfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Float</value>
      <webElementGuid>b987ffb0-127d-4a8d-a354-4ec12fe5146e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e6ad7f1e-013d-4eff-8131-b8576ccb0551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>6928abb1-39ab-4080-a6e1-b5cd03dcb729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a93521d4-cce1-434d-a480-c9f2088dba00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QL_Promissory_Note_Information_Subsidy_special_co_dealer')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QL_Promissory_Note_Information_Subsidy_special_co_dealer');</value>
      <webElementGuid>eb2a132b-01cc-411c-825d-84747e9bfb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>71e28e4e-c323-42e4-92fa-e677a60a2d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>b1008875-51dd-439c-af07-22f7010a7518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>9f828250-4b50-49d4-9b7e-9bf96ede35b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0b00e52-d350-49c3-8c6e-49ccad69842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox</value>
      <webElementGuid>ac88457d-735e-4ab0-88cf-c05f13f745a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e6dc3ef7-a05e-459a-bfa0-211b5bdb237d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_Promissory_Note_Information_Subsidy_special_co_dealer&quot;)</value>
      <webElementGuid>ef58b48a-ee98-41f1-8bb7-52676107268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>2dca8d2a-c7e9-4eba-b1aa-901ad647b1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_Promissory_Note_Information_Subsidy_special_co_dealer']</value>
      <webElementGuid>0b0c4882-11a0-4a03-9c6d-f863c3c9731a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame761']/div[2]/div/div[5]/div/div/div/input</value>
      <webElementGuid>1a648afe-817b-40c3-b13b-5c4be73ec761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[5]/div/div/div/input</value>
      <webElementGuid>8a60a483-a937-44c0-9281-053c4fd25ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_Promissory_Note_Information_Subsidy_special_co_dealer' and @name = 'QL_Promissory_Note_Information_Subsidy_special_co_dealer' and @type = 'text']</value>
      <webElementGuid>b945b6bd-9857-47b1-9d9f-53eb91adcefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
