<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total_RCBC_CMF</name>
   <tag></tag>
   <elementGuidId>d2b0adc4-3336-42e9-badf-86ce75902f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_Promissory_Note_Information_Total_RCBC_CMF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_Promissory_Note_Information_Total_RCBC_CMF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a35f7e-652f-4ab0-9b66-d2d9e50e34dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>8b0f4264-ec47-42f5-b682-688cb8f5760a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c62a084f-ba28-46a4-933a-b86e4f4c3637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>892e0880-8252-4027-8460-107fe22d1041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>147d1b2f-5259-4fd5-b5e4-f238230e88ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Total_RCBC_CMF</value>
      <webElementGuid>324a8c41-8b1f-46c0-9e95-d5f615055a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Total_RCBC_CMF</value>
      <webElementGuid>e095de2e-eeb3-426d-9f80-68ffa5184dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information.Total_RCBC_CMF</value>
      <webElementGuid>31ebde85-81b0-42f0-be63-cfbe6b923484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>182b4524-c736-4f6b-bc53-f94ff3ee358d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Float</value>
      <webElementGuid>63861d16-59f2-4951-ab09-22b39dd4aef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dad4d230-87c4-45b5-8b9d-7c00e3eb95f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>4d9b4cbc-4213-4dba-8531-9e4658f3d4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>723e99bc-0243-4721-a02a-8236d1480058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QL_Promissory_Note_Information_Total_RCBC_CMF')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QL_Promissory_Note_Information_Total_RCBC_CMF');</value>
      <webElementGuid>ae552381-5b91-4f23-8120-50ead6900c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>55f51ef7-83e5-44e2-82bf-3f7d2d591b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>1c3d9df0-e0dc-4bdf-8d2b-6babf1fe1c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>daf4f88a-32fd-4fec-99a3-e5565b344a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6a0a53f-4f70-4aa8-9a39-6daefe381b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox</value>
      <webElementGuid>3f72d897-2ad4-4a51-a11f-1a5017fad1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>292f41b5-729d-4565-b34c-eb77cef72350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_Promissory_Note_Information_Total_RCBC_CMF&quot;)</value>
      <webElementGuid>b7642b89-efa0-486c-b85b-b3fb8d53c888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>5c250d11-9465-4ece-a538-3b6ecd954c3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_Promissory_Note_Information_Total_RCBC_CMF']</value>
      <webElementGuid>ef5d3e53-bf5a-45ef-a2f4-8fe38c3d61e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame761']/div[2]/div/div[8]/div/div/div/input</value>
      <webElementGuid>a8aa8769-197f-45a2-a188-f4b28496c44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[8]/div/div/div/input</value>
      <webElementGuid>2f70651e-90da-4ffc-be19-4f174b25bd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_Promissory_Note_Information_Total_RCBC_CMF' and @name = 'QL_Promissory_Note_Information_Total_RCBC_CMF' and @type = 'text']</value>
      <webElementGuid>17658d76-c70e-4c5b-804e-89aa971261f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
