<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total_Monthly_Payment</name>
   <tag></tag>
   <elementGuidId>f5c0abbb-34b7-41a1-8d30-48c15491f4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QL_Promissory_Note_Information_Total_Monthly_Payment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QL_Promissory_Note_Information_Total_Monthly_Payment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8e99f8b-0214-4674-8a45-454cf8f9e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>4a8b35fc-edc6-410a-9756-9c6df66d5bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad1ddf63-7184-4f51-9438-0c9f83e85653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>60cac96e-fd40-4331-a064-d49633447c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value> this.title=this.value</value>
      <webElementGuid>0348e7ad-7d27-42df-b7c3-f466f1b558b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Total_Monthly_Payment</value>
      <webElementGuid>a3a3a508-798f-4bca-943c-07e5391d8567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information_Total_Monthly_Payment</value>
      <webElementGuid>eb714db5-19d7-4045-9767-a3f49d22f943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QL_Promissory_Note_Information.Total_Monthly_Payment</value>
      <webElementGuid>4e43a4a7-aa1d-4083-884b-9ef56f2316a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>dgroup3</value>
      <webElementGuid>780ec977-88a1-4a86-adf5-1c1c77749d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Float</value>
      <webElementGuid>f3535bc2-5425-4dae-a35e-cfe846882301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0192f442-182d-4ac5-956d-2a98c580901f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>d60a4e87-6ba4-4b34-a7be-e935c1b90c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>69a17b87-0289-4167-9358-7985cb2c69cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QL_Promissory_Note_Information_Total_Monthly_Payment')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QL_Promissory_Note_Information_Total_Monthly_Payment');</value>
      <webElementGuid>9d0ac9e9-b650-4766-a628-6b1fefa8b61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>36d7dd10-03b1-47f1-b7a4-f6fbe59683cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>04b23d7b-a9b7-4466-93e9-5258ded788f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>c4f57f1b-2612-487d-95cd-8e8ba6085eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51bdcf70-5059-471e-ad95-4c9579275eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input control-class inputStyle textbox</value>
      <webElementGuid>b4a58b87-7577-4477-97d3-bf23d44d78aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>54a1b9e3-2468-4daa-a87e-120f4d689941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QL_Promissory_Note_Information_Total_Monthly_Payment&quot;)</value>
      <webElementGuid>4deb5482-18c9-462f-8468-ec2b7d0bcdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseLoanInformation/iframe_Form_ngformIframe</value>
      <webElementGuid>166980e9-c2f7-4e45-9942-4246751a440d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QL_Promissory_Note_Information_Total_Monthly_Payment']</value>
      <webElementGuid>394a038e-5267-495a-a050-2e7233e1800d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame761']/div[2]/div/div[7]/div/div/div/input</value>
      <webElementGuid>1f1d2778-f305-4e31-a38a-4982e4799b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div[7]/div/div/div/input</value>
      <webElementGuid>093ffd88-9ce4-40b2-a79d-cda0b87025c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'QL_Promissory_Note_Information_Total_Monthly_Payment' and @name = 'QL_Promissory_Note_Information_Total_Monthly_Payment' and @type = 'text']</value>
      <webElementGuid>c7f7655b-db73-4cd6-90d5-cd15f7186764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
