<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EncoderForWithout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2b89ba60-c07f-4a86-bbdb-eef3c8c3d94c</testSuiteGuid>
   <testCaseLink>
      <guid>2fc1cdd7-e68d-49d9-8779-75c2f1bac9e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5fafe789-a7b8-49ed-b4e6-29116fb63532</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/HomePage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>636e1c03-a8b2-476c-ad2c-d6dfd563802a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/ClientInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0919976a-b6f6-4655-afcd-fcc8278dabc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/CollateralInformationWithout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1a998730-2888-4691-bbfd-ddcf882cfb65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/LoanInformationWithoutAPI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>18de7999-db95-4dd9-b7ec-fa61f957e376</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/PaperbaseLoanInformationWithoutSTP</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>marketingPromoCode</value>
         <variableId>5a2db45d-dbb7-45b3-ad68-16e33e1fc867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Downpayment_Amt</value>
         <variableId>35a67b93-c10a-463a-800c-fbc6de7094b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Actual_Cashout</value>
         <variableId>8b8b9ff8-aba1-420e-819b-67c7dc843883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanTerm</value>
         <variableId>7c81578d-c3c2-4c98-9269-d13ce1806a38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>insuranceType</value>
         <variableId>3449433c-e232-4761-b88e-2b8b944ca532</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>loanPurpose</value>
         <variableId>e005adc6-77b6-4518-8944-bdab9d55f1e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>modeOfRelease</value>
         <variableId>d5495358-2054-48c7-921f-015a92addbc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Scheduled_Unit_Release_Date</value>
         <variableId>d62c730f-ef08-4c5f-b24f-d30e1db1bcff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Actual_Unit_Release_Date</value>
         <variableId>5598c66e-5b88-4704-a702-e22d8f324717</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Total_CMFCollectedby_Dealer</value>
         <variableId>5ac09198-a445-4cb0-aa97-36f3c91a49af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Payment_Type</value>
         <variableId>5c761d6a-ef2a-4174-8a63-8d06156e6859</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PaymentFrequency</value>
         <variableId>f6584d10-dc6a-4b6f-8f61-b2c69ef3b6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>18de7999-db95-4dd9-b7ec-fa61f957e376</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mode_Of_Payment</value>
         <variableId>8671a836-82ae-4f62-a519-6c9f85ce75fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a676c42-f497-4df5-8f67-8f961b5b8fe3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/DocumentChecklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7309573c-8db6-4637-b854-7cfc8f3c6cce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/CheckEligibility</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f9bbf86e-66ca-47e2-a25d-7cae0ea24599</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/CreditEvaluation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3e58d8fc-00fb-4e5c-831c-0aae765812ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/CreditInvestigation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>36988153-7efa-4d0a-a0e9-46d5f938e8f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/InsuranceInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4bb8313b-8928-4210-8e4d-d6f0a4f5ab5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/DisbursementInformation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>69b5a8f1-aaf3-4ceb-9556-43c56c8712d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/Encoder/Action</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>08b84a29-ae77-4d2d-b536-b586c2bd05a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LogOut/logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
