<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VIEW</name>
   <tag></tag>
   <elementGuidId>e432f9dc-1c3b-4e88-9c5a-639dbb2b9ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.control-class.control-label.fmarginbottom0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;if(window.onRowClick){callCustomRowLinkMethod(this,'onRowClick','listapplication');}cancelBubbling(event);return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2282731f-18a4-44e8-8acc-4672f6661e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onRowClick){callCustomRowLinkMethod(this,'onRowClick','listapplication');}cancelBubbling(event);return false;</value>
      <webElementGuid>9d9c2d47-495f-4bfd-a304-af50e490d478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary control-class control-label fmarginbottom0</value>
      <webElementGuid>7469f55c-dfe8-4300-a0ca-4a6858fc1a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIEW</value>
      <webElementGuid>01c4fe7e-4062-4833-9eba-f347f03dbd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listapplication&quot;)/tbody[1]/tr[@class=&quot;rowinhtml&quot;]/td[@class=&quot;fpadding3 fminwidth90&quot;]/a[@class=&quot;btn btn-primary control-class control-label fmarginbottom0&quot;]</value>
      <webElementGuid>f91f0f22-233d-4685-abaf-c20517f78ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;if(window.onRowClick){callCustomRowLinkMethod(this,'onRowClick','listapplication');}cancelBubbling(event);return false;&quot;]</value>
      <webElementGuid>4ecab351-4b15-432b-8eb8-bc6ac15a7480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='listapplication']/tbody/tr/td[7]/a</value>
      <webElementGuid>a4135568-89ac-4072-bd00-d6f2347eeb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VIEW')]</value>
      <webElementGuid>93475c3b-7b82-43ea-b11f-0ba9062f44bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WIId'])[1]/following::a[1]</value>
      <webElementGuid>15810e12-099f-49ce-b340-bb0cce636e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW'])[1]/following::a[1]</value>
      <webElementGuid>039321ec-06b5-47fd-a287-5efc4fe8fdf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW'])[3]/preceding::a[1]</value>
      <webElementGuid>060ceb90-c34c-4bd2-a98f-685a51ea8e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW'])[4]/preceding::a[2]</value>
      <webElementGuid>110e3504-15b4-40f4-add1-e51b9e78fd50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>7ef3716c-1177-460a-b03a-d7852b807b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'VIEW' or . = 'VIEW')]</value>
      <webElementGuid>5404af39-8839-48f9-a753-4c9630fee87f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
