<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_All ApplicationDealer Pre ReleaseDea_4ef469_1</name>
   <tag></tag>
   <elementGuidId>dfd20283-bec9-4031-93a3-03d15a2789b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stagename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='stagename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>613704d5-ce5c-4e76-9d4d-4e4c0d4ed271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>aa6b88be-3361-43f5-9a06-3b8762c12eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>fef08316-e354-4ae7-bd30-0582991e69f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dealer Pre Release</value>
      <webElementGuid>412a0274-81fb-415c-adfa-d8df2f4063ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>cd8d4733-27c2-4b86-9cfb-a222e0b3e6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stagename</value>
      <webElementGuid>160cc0e5-cdc2-4d8a-9a1f-def79e06c34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svt</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>ff84cb63-53e4-44fc-987a-d3d2ccae37b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>762618a1-f4a1-42e3-89d6-8234492e3a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);if(window.onManageLoan){onManageLoan(this,event);}</value>
      <webElementGuid>dbd7c3e6-317a-4c17-98fe-c9c474eb0525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle</value>
      <webElementGuid>9cd5801f-69af-4980-b176-71e90affbd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal</value>
      <webElementGuid>f975a7ca-a7c6-4872-99d7-aede5decb7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stagename&quot;)</value>
      <webElementGuid>90816b05-8384-4484-880d-b486428e2510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='stagename']</value>
      <webElementGuid>39afa783-096d-420e-9e3b-07dbc93ac504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tablepage']/div/div/div[3]/div/div/div/div/select</value>
      <webElementGuid>44872341-7164-491c-b908-59923b1c043a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of all auto loan application'])[1]/following::select[1]</value>
      <webElementGuid>0e82415c-9819-4815-bc03-f099630e3190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::select[1]</value>
      <webElementGuid>9e7a262f-5dd2-4764-a775-aae32574281e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show :'])[1]/preceding::select[1]</value>
      <webElementGuid>103f3c32-ed0f-43da-ae4b-93c2cce26a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[3]/preceding::select[1]</value>
      <webElementGuid>2e241b51-bdaa-446c-b8f2-66fda1a235b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>96a92b4f-bcb6-4322-b432-bd2321fb8eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Dealer Pre Release' and @id = 'stagename' and @name = 'stagename' and (text() = 'All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal' or . = 'All ApplicationDealer Pre ReleaseDealer Post ReleaseReworkPortal')]</value>
      <webElementGuid>3b55eea4-65b6-4f5e-ae2b-6304215e3f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
