<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PreChangeInCashout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>76fc3206-c4d8-4050-bf66-80ef38e39035</testSuiteGuid>
   <testCaseLink>
      <guid>eae51a27-75b1-4784-a487-1553ab5e6da1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/LoginPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7707ab53-d9f5-4124-863a-53ebb1731ec2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e882d49f-8449-498f-ab6e-b3dd659c6dd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/ApplicationPageForPreAndPost</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f124f883-295b-417a-b201-157bcf482765</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ApplicationSecPreData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f124f883-295b-417a-b201-157bcf482765</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>show</value>
         <variableId>5c4e6695-bd7b-4104-bbd8-0abc85af35d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f124f883-295b-417a-b201-157bcf482765</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sortBy</value>
         <variableId>b52673a0-3913-4514-83d0-f6aff6c54b36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>235fdd5a-0134-42f1-8777-4079963d847a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/CustomerDetailForPreRelease</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5fddfdc2-6915-492d-aade-7a1c2e73d41b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PaperbaseAmendmentWithoutAPI/PreReleaseChanges/LoanInformationForPreReleaseCashoutChange</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff7e5880-3501-424e-a444-8b81d630f7e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4262d358-3f36-4d9d-aed8-83653670778c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2998121e-d9f4-4f7d-b4d3-a0d3538b9ef3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70a12d7f-6c76-4663-85f5-683dc9cab75f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17a3fff9-59c4-4859-abad-e7bada3318a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18e5be5-c621-48bb-a4e6-c3fbd47f9765</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>324e2ed5-2731-4500-821e-7219c7298d66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440211bd-8615-41f5-87b0-f324e8c306fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f575487e-9403-43ef-a432-c2a4e6dde090</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f7196f-8f68-4f07-b942-8e56f97b23b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56625906-e929-4094-937b-0488a55715dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3bfac2a-ea67-4d35-88bb-10476ba5f8ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/DocumentChecklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>52d1b454-590b-464e-a392-30daa8b936a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/CollateralInfo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>64bd8725-bda8-48ae-a39a-a1de91970a07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Paper_STPWithAndWithoutAPI/PreAndPostRelease/DisbursmentInfoNew</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
