<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccutySaveChanges</name>
   <tag></tag>
   <elementGuidId>92a0cac2-205e-4eb8-b9ca-814a57ebdfe7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAdvancedListviewchanges_table716</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveAdvancedListviewchanges_table716']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3dde6cc0-e62a-4f25-8800-94e5566d6206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>9635f79d-7136-4462-bc74-e70a06188c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modifyAdvancedRowTableData('table716');</value>
      <webElementGuid>f8b68134-0d16-4eb5-af01-df6c10fd9238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAdvancedListviewchanges_table716</value>
      <webElementGuid>7fcbf38a-2391-4fc4-b20e-f191abdb2f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>535ecacf-973f-4539-960e-ae2aede20132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>f326012e-54e5-4028-a75d-48935b40e2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAdvancedListviewchanges_table716&quot;)</value>
      <webElementGuid>1128a7d8-7e39-44d7-968b-39cd59785835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>74ebe20d-788b-4fe6-8f19-c52b52bb4358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveAdvancedListviewchanges_table716']</value>
      <webElementGuid>8c9361e2-dc5f-4e7c-9aba-6da77a92df97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedListViewModalContent']/div/div/span[2]/div[2]/button</value>
      <webElementGuid>c17eeff1-6bba-4ba6-818e-e0f9b5e2251c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accuity'])[2]/following::button[1]</value>
      <webElementGuid>b916ed1d-09af-4f0d-b340-cbd291942324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[566]/following::button[3]</value>
      <webElementGuid>21376494-50ae-40fd-9586-187c18f03ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Name'])[14]/preceding::button[2]</value>
      <webElementGuid>04e58465-e7df-43c8-84e4-2a30e0724580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[294]/preceding::button[2]</value>
      <webElementGuid>2712256c-c826-4d6a-acba-608b99bc3ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[2]/button</value>
      <webElementGuid>411bc3ce-a729-42e7-bad9-342f0cfda2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveAdvancedListviewchanges_table716' and @type = 'button' and (text() = 'Save Changes' or . = 'Save Changes')]</value>
      <webElementGuid>ceab7044-09d8-4ce1-8237-4b83ba03593a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
