<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accuity_Remarks</name>
   <tag></tag>
   <elementGuidId>d71ee67a-c588-47db-a41d-8c40b4d6e47e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QNL_Accuity_Remarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QNL_Accuity_Remarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa527f70-c500-4976-8597-31871e2a2bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c87c0c18-4383-48d3-b9a3-03109e463440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input advancedListviewControl   control-class inputStyle textbox</value>
      <webElementGuid>4a91132e-b56e-4539-82fc-d2a7db9f28e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39583f98-5b5b-4376-be39-750e8fcd0f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>de309042-09d3-436b-8399-b663213afab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>f65c0f56-645c-4582-a240-4d5cca34c025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>480430a0-60c1-4338-8dbe-5ba9c84c2044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QNL_Accuity_Remarks')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QNL_Accuity_Remarks');</value>
      <webElementGuid>c25deee3-a4bc-443b-9e41-018b2fe324fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>25aa5012-ed6d-4672-bd36-418385a6a633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>6a98290d-a873-4f11-b39f-5e11f3569e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QNL_Accuity.Remarks</value>
      <webElementGuid>f5b393f3-37da-45a2-8a4f-cb8c45a4c2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QNL_Accuity_Remarks</value>
      <webElementGuid>b344b330-13e5-45d7-9135-b303ca1a0434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QNL_Accuity_Remarks</value>
      <webElementGuid>21b76e30-4a9f-4450-9bc7-85a95e5ea193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>ffa17b2d-e394-4ed7-b03f-4a1e9058905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ee12045e-9302-446d-8b19-c8a6852c488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7817a96-2f63-46bc-8e8b-28cd17447083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>34dd570b-234c-40ec-b16b-2eb6a8cd9659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QNL_Accuity_Remarks&quot;)</value>
      <webElementGuid>1fa0db90-9145-40ca-a582-37a139504d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>e331002c-877d-4333-aa47-ce8a0768ceac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QNL_Accuity_Remarks']</value>
      <webElementGuid>62dd2f6a-8b09-4597-922c-e23ba708cac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table716_frame691']/div/div/div[9]/div/div/div/input</value>
      <webElementGuid>ecb6e936-1d5e-4787-b995-507af9c980b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[9]/div/div/div/input</value>
      <webElementGuid>83d43676-b086-467f-8b4a-a82f275f6ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'QNL_Accuity_Remarks' and @id = 'QNL_Accuity_Remarks']</value>
      <webElementGuid>137a5afc-c6d4-47f8-8812-b1e51291804a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
