<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccuityBorrowerType</name>
   <tag></tag>
   <elementGuidId>33063f3d-3320-4704-aed3-29fddc846b83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QNL_Accuity_Borrower_Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='QNL_Accuity_Borrower_Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48ad35fa-677a-4b8d-81cf-f6f16795565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class form-control1 inputStyle advancedListviewControl</value>
      <webElementGuid>9d96a3e9-0a68-4ce2-a494-4a84ef20cc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>c068633a-5281-4004-b8ed-eae984190a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QNL_Accuity.Borrower_Type</value>
      <webElementGuid>fce5ce38-9ec6-4a48-94f1-12bc9b256468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>bdee6dcb-57a3-4968-bfd2-60b0eac56875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QNL_Accuity_Borrower_Type</value>
      <webElementGuid>504afa43-5f7c-4e78-acd2-afdb86d649de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QNL_Accuity_Borrower_Type</value>
      <webElementGuid>6851ecb0-855c-4e5b-9469-8652d512478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>cbcfed21-fc6a-41d1-b4dd-06a2ab745dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QNL_Accuity_Borrower_Type</value>
      <webElementGuid>71c18880-351b-49d1-aca4-410c97579fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.selectedIndex >= 0 ? this.options[this.selectedIndex].title : ''</value>
      <webElementGuid>2555beab-e90a-43e9-a3b3-099861fc3a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectPrincipalCo-BorrowerAttorney In-Fact</value>
      <webElementGuid>1dfbb9cf-1f0f-4826-a7fd-ad3c7e6f3b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QNL_Accuity_Borrower_Type&quot;)</value>
      <webElementGuid>a867655b-3df9-4384-85e8-31bc74a65ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>285199ad-8422-4823-b252-48aad74801b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='QNL_Accuity_Borrower_Type']</value>
      <webElementGuid>1046ed8a-4b31-4f9a-9f73-0bb127f2860e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table716_frame691']/div/div/div[8]/div/div/div/select</value>
      <webElementGuid>d4c3f1a9-0bad-4a4a-999f-7bde78a4cd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[573]/following::select[1]</value>
      <webElementGuid>9d52131b-e029-4275-8d58-a774af6d570b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[96]/following::select[1]</value>
      <webElementGuid>38aa470b-6119-441a-ae39-554827c0a41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[14]/preceding::select[1]</value>
      <webElementGuid>494780c2-8c1d-4644-8fd4-2c49e57c1df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[574]/preceding::select[1]</value>
      <webElementGuid>caec1890-eef2-41bb-b047-ae1224dac55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[8]/div/div/div/select</value>
      <webElementGuid>b5f26c3f-1fee-4c19-aa3a-ebc71f937b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'QNL_Accuity_Borrower_Type' and @id = 'QNL_Accuity_Borrower_Type' and @title = 'Principal' and (text() = 'SelectPrincipalCo-BorrowerAttorney In-Fact' or . = 'SelectPrincipalCo-BorrowerAttorney In-Fact')]</value>
      <webElementGuid>2a815179-fe6c-448f-b6f0-81c7d495fbc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
