<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccutyCheckEligibility</name>
   <tag></tag>
   <elementGuidId>f97751ee-00fb-4794-a2cd-0908ebd53af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table716_button447</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='table716_button447']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8842e692-48e8-4c81-a0a6-efe725cf628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer advancedListviewControl</value>
      <webElementGuid>1b26b0e6-4724-4e45-b808-f389e7baeb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c53b05f-d629-41c8-b96d-7c8316327be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table716_button447</value>
      <webElementGuid>f0d1d164-3225-460d-a9a4-a28f3ff0024f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table716_button447</value>
      <webElementGuid>fa39e008-425d-4c86-9077-d79f8e21b7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>b7992758-90e1-4fc5-bccb-5397c0c3f56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table716_button447&quot;)</value>
      <webElementGuid>0d443a17-33d2-4666-919a-e52c2c17bb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>a5cf869c-f8d0-4ce8-a368-d33457daa1f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='table716_button447']</value>
      <webElementGuid>f7ef3f5f-6ec6-4dea-a33f-066a0fb5526b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table716_frame691']/div/div/div[10]/div/button</value>
      <webElementGuid>418c1485-70ff-4fa1-b0f7-011ce9505131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[575]/following::button[1]</value>
      <webElementGuid>af6aebb8-bb66-4a2f-90fc-894b12d6558f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[286]/following::button[1]</value>
      <webElementGuid>ae57b837-9e90-4f8d-b799-3fd4750f5aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accuity Result'])[2]/preceding::button[1]</value>
      <webElementGuid>30313c0f-f8ca-469d-beb4-0c9379849678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[298]/preceding::button[1]</value>
      <webElementGuid>634f4547-a420-4517-bd7c-9052012d2687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>a232d8eb-bf7a-4c2f-ba19-ba5d36d33df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'table716_button447' and @id = 'table716_button447' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>2719f5da-b1ab-40d5-a95b-c8e38da3b160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
