<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Accuity_Case_ID</name>
   <tag></tag>
   <elementGuidId>a38313b1-740c-4e52-9016-760a2600d26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QNL_Accuity_Case_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='QNL_Accuity_Case_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30baf9bc-7d48-4019-a668-daa57793d6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>floatlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d020daa1-d36f-45de-afb7-3039fc42edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input advancedListviewControl   control-class inputStyle textbox</value>
      <webElementGuid>b3646d9b-30a3-4536-8c92-98d2faec495b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ac30727-1daf-4edf-88da-933cad4ec735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datatype</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>d4054d7b-a0ee-4dab-934e-b1f5927f4cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ctrOnchangeHandler(this,1);</value>
      <webElementGuid>9276dd92-3da6-4f3c-94dc-b342da0d55f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>constraintOnPaste(this,event);</value>
      <webElementGuid>8b6b3f9c-2ff8-40b9-a0c8-ed918c449412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>if(!TitleCharacterValidation(event,'1','QNL_Accuity_Case_ID')){return false;}if(event.keyCode==114){event.preventDefault();} ; titleMaskingValidation(event,'QNL_Accuity_Case_ID');</value>
      <webElementGuid>b7a12e5f-c8fd-4f39-bbf3-1087f652d725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>13dffa38-b114-4c72-a44c-36a23776f2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>43f9a17e-a429-4ae2-b0db-11a4a9502a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>42d38b61-540e-4f94-902e-672a28677fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofvalue</name>
      <type>Main</type>
      <value>Float</value>
      <webElementGuid>edc77060-9091-46bf-8653-1326a9e8098c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>87ff8f53-2cd1-4afd-ab3f-f91f937a2de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dataclass</name>
      <type>Main</type>
      <value>QNL_Accuity.Case_ID</value>
      <webElementGuid>894e3fd7-1e94-4e07-883d-a3324d842f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QNL_Accuity_Case_ID</value>
      <webElementGuid>c184db1e-8e05-4ca3-848b-65bdc31e79bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QNL_Accuity_Case_ID</value>
      <webElementGuid>437ae02d-5f7d-488d-b0e4-2a609ba7d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>this.title=this.value</value>
      <webElementGuid>c77fae47-eb3c-49be-a575-a73118e5ff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9dc7ae88-870f-426b-a775-59a2298037e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38f31c06-c065-40bb-8192-59797b1fedea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formattedvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>e5b8e7bd-3990-43f3-ab18-78d65004fba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QNL_Accuity_Case_ID&quot;)</value>
      <webElementGuid>2924673f-cf3c-4eea-bc7d-1e3ed1ff498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>6e3dffa0-a576-4779-8066-9da84eaf2f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='QNL_Accuity_Case_ID']</value>
      <webElementGuid>08768dc2-bd1e-4bc0-aed2-e227ff5f4c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table716_frame691']/div/div/div[7]/div/div/div/input</value>
      <webElementGuid>9af3191d-1f58-4722-b7f8-87ff7efa930d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[7]/div/div/div/input</value>
      <webElementGuid>6ae3d6b1-23fb-4270-a048-6711e44a395b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'QNL_Accuity_Case_ID' and @id = 'QNL_Accuity_Case_ID']</value>
      <webElementGuid>97506bcc-0822-4dd7-9933-291a9df03106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
