<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccutyPrincipal</name>
   <tag></tag>
   <elementGuidId>a3ddb289-87fd-46d3-85fb-14673835e42f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table716']/tbody/tr[1]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>57100347-238f-4e3f-bcdc-96bd31d60d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelname</name>
      <type>Main</type>
      <value>Borrower Type</value>
      <webElementGuid>c66c8faa-a20b-47ee-af63-90754ef0c665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class control-label fmarginbottom0 inputStyle listviewlabel </value>
      <webElementGuid>ca30261f-c47c-4717-9456-9fac65ef4e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>4920ebdd-e924-4323-af29-6937449d205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PB</value>
      <webElementGuid>f18b1974-5659-4121-af45-dbfe576c3c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>92d504d7-ced9-4315-9bae-19553c0f76b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table716&quot;)/tbody[1]/tr[1]/td[@class=&quot;fpadding3&quot;]/label[@class=&quot;control-class control-label fmarginbottom0 inputStyle listviewlabel&quot;]</value>
      <webElementGuid>a9772e4f-e4c4-4654-88f4-01526b22f2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>0c7bb0e0-95bf-47d0-8314-203735b6e9a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table716']/tbody/tr/td[2]/label</value>
      <webElementGuid>431a4e79-ccd7-4624-89e5-2edc1a5e85ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[16]/following::label[2]</value>
      <webElementGuid>e36197cb-83f7-4d49-87f5-732e104ce902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accuity Status'])[1]/following::label[2]</value>
      <webElementGuid>602a0e00-1247-4748-ae9f-2f7f5caaca37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a b c'])[7]/preceding::label[1]</value>
      <webElementGuid>d2ab4b82-f3ff-4e41-904a-23056e5a9267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAP NFIS'])[1]/preceding::label[6]</value>
      <webElementGuid>e143606a-2360-41e5-a618-9f131947322e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/table/tbody/tr/td[2]/label</value>
      <webElementGuid>f476f432-e764-447e-b234-145517930cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'PB' and (text() = 'Principal' or . = 'Principal')]</value>
      <webElementGuid>5740b725-6076-4082-acc9-b17660bb40e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
