<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DOSRICheckCheckEligibility</name>
   <tag></tag>
   <elementGuidId>0dc29815-a966-4729-b233-3dd951d90870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button794</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button794']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f04fe91c-f075-4688-b20f-ec1b63f2554b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onClickDOSRI){onClickDOSRI(this,event);}</value>
      <webElementGuid>d6315e1c-4b3c-4ea8-8616-cc0ee07a5784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer  tableButtonControl</value>
      <webElementGuid>76b2581d-00ce-42dd-a45b-120e07aedb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdc71b26-a579-49a1-8d9f-360450b79dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button794</value>
      <webElementGuid>853859b7-1f8a-4283-a34d-c3bac95eee10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button794</value>
      <webElementGuid>e735fb77-57ae-4b9d-a0fa-c5ec9ee83ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>5ceab527-12a7-46e2-9827-16d7eb11d1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button794&quot;)</value>
      <webElementGuid>3f427518-faeb-4ccf-982a-2d97debc2912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>268c83f7-3521-4e9e-b94a-e5e2651c353e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button794']</value>
      <webElementGuid>d1223ed5-7319-4086-a3ea-32a81207506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listViewModalContent']/div[2]/div[2]/div/div[7]/div/button</value>
      <webElementGuid>9ab7c1d6-2610-4a53-ab53-f7fa40b9109b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[563]/following::button[1]</value>
      <webElementGuid>3c17bdae-a2a4-4a69-ab5a-fa2f6d7c2b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[280]/following::button[1]</value>
      <webElementGuid>3dc7819f-3f59-4d94-be2a-9fec81087d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[13]/preceding::button[1]</value>
      <webElementGuid>47e82a7a-595d-4da0-bb10-12363af164f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[564]/preceding::button[1]</value>
      <webElementGuid>3d220b3f-476c-443a-a43e-a8b490a009ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>40044f2f-2abe-4740-aa04-768dddaea878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'button794' and @id = 'button794' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>09999dcd-598d-4c3a-b238-8ae340270eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
