<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DOSRICheckSaveChanges</name>
   <tag></tag>
   <elementGuidId>281051c3-91f4-4aaa-99f4-f8ad1c787f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#savechanges_table823</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='savechanges_table823']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fde7bd55-fcc9-4135-8af2-3f19ad928092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>7396efbf-2407-4085-9fbb-ce0b4bc50a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modifyRowTableData('table823');</value>
      <webElementGuid>52bb4e2f-a1b7-47cd-a176-741a4a91ae86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>savechanges_table823</value>
      <webElementGuid>25d6de43-f7de-4cea-9297-ff5879ce7453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ecb1c13-d6bd-4001-b778-ed969e9bb312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>4f3178f1-3326-478e-88e1-7ff851928510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;savechanges_table823&quot;)</value>
      <webElementGuid>84230499-4a36-4e69-9b8f-94795f208089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>e89ac282-18a7-4187-9650-7a23aa5afbfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='savechanges_table823']</value>
      <webElementGuid>c693c4aa-d55b-4729-bae2-9cca3f2c9545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='listViewModalContent']/div/div/div/span[2]/span/button</value>
      <webElementGuid>dc37dc01-a0a5-4846-a375-7fabf5f369c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOSRI Check'])[2]/following::button[1]</value>
      <webElementGuid>2a210e67-719c-4bc9-9157-9fd29dc45776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[3]</value>
      <webElementGuid>f6279ed2-c860-486e-b973-30cffa0bc9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Next'])[1]/preceding::button[1]</value>
      <webElementGuid>d576ab7d-9ead-4cef-9aac-7568e5902baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and Close'])[1]/preceding::button[2]</value>
      <webElementGuid>bfff0034-08aa-4402-b7be-ae8d42af9176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Changes']/parent::*</value>
      <webElementGuid>df9fc33e-91f8-4828-be8f-610d64ecd9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/button</value>
      <webElementGuid>0cfb7e6e-0ea3-4602-9a9a-e55bf7840d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'savechanges_table823' and @type = 'button' and (text() = 'Save Changes' or . = 'Save Changes')]</value>
      <webElementGuid>14cdde61-f383-45ae-8af7-3655a217fe68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
