<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DuplicateApplicationCheckEligibility</name>
   <tag></tag>
   <elementGuidId>2641ed31-521e-45c0-854f-8bb936a72d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table711_button442</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='table711_button442']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca72ddc0-6cfa-433c-8ad7-80026cce00d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onClickDedupCheck){onClickDedupCheck(this,event);}</value>
      <webElementGuid>83579992-5020-4cd0-bf8b-c6a77a15fe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer  advancedListviewControl</value>
      <webElementGuid>e0d63e0a-e85a-4469-8ce2-d3406e7cb095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7a8bda3-1331-4908-9551-6fa0980e965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table711_button442</value>
      <webElementGuid>fd4bfbd5-ce47-4b12-bc9c-26dfd5647fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table711_button442</value>
      <webElementGuid>a4bd9b63-8938-48ea-ba96-ee7ab1ac1185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>a48ca4e9-59cf-41da-aef7-c539b7e5dbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table711_button442&quot;)</value>
      <webElementGuid>8cb966ac-5a34-48fc-97d8-c2bae92c044c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>b5490855-943a-4c89-bc83-53d621c8b708</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='table711_button442']</value>
      <webElementGuid>002156ed-0575-45d3-9389-8ef6c4d297fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table711_frame686']/div/div/div[10]/div/button</value>
      <webElementGuid>6553afb5-61b8-40e5-9ad1-0889c9fe7e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[566]/following::button[1]</value>
      <webElementGuid>7823093c-23a5-4fca-a68f-71afb1953244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[281]/following::button[1]</value>
      <webElementGuid>a7032ea0-e895-42d2-84bc-5ffa24c11708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[13]/preceding::button[1]</value>
      <webElementGuid>23c0d50d-16c9-4410-b678-53716171f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[567]/preceding::button[1]</value>
      <webElementGuid>f02b5899-823c-4312-960c-3245126f5e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button</value>
      <webElementGuid>bc3bcfa0-a85c-4a9d-8e33-5ebc2a0160d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'table711_button442' and @id = 'table711_button442' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>484471c3-7722-49d7-8f06-8ec3f162901d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
