<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DuplicateApplicationSaveChanges</name>
   <tag></tag>
   <elementGuidId>b73d838f-8a1c-4a68-92a2-98f7cb750515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAdvancedListviewchanges_table711</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveAdvancedListviewchanges_table711']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aab47d12-54a5-4041-9d21-d694a57f8887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>fd0b29b2-2f32-47e8-abad-c2fad6187324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modifyAdvancedRowTableData('table711');</value>
      <webElementGuid>220ccf9c-6e8e-4fe9-9225-854138bffc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAdvancedListviewchanges_table711</value>
      <webElementGuid>fd2adb13-3099-4607-8704-f0ed2b180a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42af7420-697b-4c92-974c-0711828b13f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>85079d02-ebe7-459a-b211-50245dcda501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAdvancedListviewchanges_table711&quot;)</value>
      <webElementGuid>abb59906-074b-4f67-99b8-d6ffcba91b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>61aab1ae-a198-4ca6-bf9b-7334c79f6995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveAdvancedListviewchanges_table711']</value>
      <webElementGuid>bd3fe107-9073-40b1-9ad0-a6f6978b4db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedListViewModalContent']/div/div/span[2]/div[2]/button</value>
      <webElementGuid>0b4e6618-a2b4-4a9c-9da3-1615a0ee8944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate Application Check'])[2]/following::button[1]</value>
      <webElementGuid>2d6394a1-5170-4491-bbde-c7a7b651d29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[3]</value>
      <webElementGuid>0acbe460-68cb-445d-88a3-2e4963014849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant_Name'])[1]/preceding::button[2]</value>
      <webElementGuid>0ac95290-04ee-42ec-a28a-bca35ff9f579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[288]/preceding::button[2]</value>
      <webElementGuid>b7ec28de-4232-4f16-a905-8423b8c0e48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save Changes']/parent::*</value>
      <webElementGuid>248e30b7-376c-40ba-8d8b-0d7e31ce00bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[2]/button</value>
      <webElementGuid>78cc1315-f18f-49ed-b55d-510a9dcacbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveAdvancedListviewchanges_table711' and @type = 'button' and (text() = 'Save Changes' or . = 'Save Changes')]</value>
      <webElementGuid>0081ea1d-e763-4628-9f0c-cced62c25ea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
