<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DuplicateApplicationCoBorrower</name>
   <tag></tag>
   <elementGuidId>0610c501-0921-4d6e-a53f-9096b2baf16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table711']/tbody/tr[2]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>94452f6f-d00a-4bfe-8b27-e03987026d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelname</name>
      <type>Main</type>
      <value>Borrower Type</value>
      <webElementGuid>2f704352-3a6e-448a-a106-8dcc191fac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class control-label fmarginbottom0 inputStyle listviewlabel </value>
      <webElementGuid>0f0487e8-e71a-46f8-a8e4-680500fb4083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>d699b97f-592e-4232-af38-ffcf75b192eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PB</value>
      <webElementGuid>e4754faf-0e1c-409c-8fba-9962068b3dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>7d3b0d08-c961-460e-9f22-f0f943f922ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table711&quot;)/tbody[1]/tr[@class=&quot;selectedAdvancedListviewRow&quot;]/td[@class=&quot;fpadding3 advancedListviewrowToModify&quot;]/label[@class=&quot;control-class control-label fmarginbottom0 inputStyle listviewlabel&quot;]</value>
      <webElementGuid>02686dd6-53b4-435f-b90e-b583f46038d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>65e0f769-4a80-4358-9234-54ae042a85f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table711']/tbody/tr/td[2]/label</value>
      <webElementGuid>6aba7390-d8df-4e55-8676-0e14e661b081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[9]/following::label[2]</value>
      <webElementGuid>ff5c7cd9-da07-4225-a626-16f9278f9cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dedup Status'])[1]/following::label[2]</value>
      <webElementGuid>a4880673-0876-4e40-b41e-db28a8e9a7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a b c'])[1]/preceding::label[1]</value>
      <webElementGuid>6b1ef7d7-31ac-4bbf-ad2a-5966752900ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPT Check'])[1]/preceding::label[6]</value>
      <webElementGuid>17ea89c3-8033-4088-baf1-a3a5ad27fcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/label</value>
      <webElementGuid>f801824b-d526-41f9-9792-8f9be8e1a8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'PB' and (text() = 'Principal' or . = 'Principal')]</value>
      <webElementGuid>20d15ddf-403a-49a7-8dd4-14ad61beb19c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
