<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Form_ngformIframe</name>
   <tag></tag>
   <elementGuidId>451ef70d-753b-4e1e-8fe4-93e7b33118e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngformIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ngformIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4bacfa05-1a1c-4acb-b94e-58c7efefefda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngformIframe</value>
      <webElementGuid>3751a565-a9be-4319-9c91-d0cb3d2ba188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000433&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000433&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=3b5f556c-3675-4d3d-91f7-1a04d203d4c8&amp;WD_RID=dbedfcb0-3a76-4912-8c72-a5a3bc13b421&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=a1c1bf1d-f2dc-456f-bca6-f594a9c7ccd2&amp;ArchivalMode=N&amp;mobileMode=</value>
      <webElementGuid>d0fcd961-a0e0-435b-ba05-4c102e5e29c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>19ee299b-9792-4c79-bf8f-a284d09c23b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee36b3a1-94cd-4c80-9333-beb02417679e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bdf3a92a-5414-44f8-9db0-56090c69131b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ae297ff-0807-47ea-ab43-0e2a4bac81b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngformIframe&quot;)</value>
      <webElementGuid>3fbb33e9-17f9-456e-841f-d9e648dd90bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ngformIframe']</value>
      <webElementGuid>ce540b58-0a45-43de-b519-5d5fd651752a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formDiv']/iframe</value>
      <webElementGuid>5cc953b3-5bca-4cf5-ac16-56b227c6e624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>2fa8c874-46e1-44c1-b670-ed545fa97c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ngformIframe' and @src = '/webdesktop/CustomForms/Form.jsp?wdesk%3Apid=LOS-0000000433&amp;wdesk%3Awid=1&amp;wdesk%3Ataskid=&amp;wdesk%3Asubtaskid=0&amp;ProcessInstanceID=LOS-0000000433&amp;WorkitemID=1&amp;taskid=&amp;subtaskid=0&amp;TargetWar=PROCESS&amp;ProcessDefId=1&amp;ActivityId=13&amp;WD_SID=3b5f556c-3675-4d3d-91f7-1a04d203d4c8&amp;WD_RID=dbedfcb0-3a76-4912-8c72-a5a3bc13b421&amp;FormBufferFolder=rcbcuat_1_13&amp;FormBufferName=14&amp;fid=Form&amp;rid=a1c1bf1d-f2dc-456f-bca6-f594a9c7ccd2&amp;ArchivalMode=N&amp;mobileMode=']</value>
      <webElementGuid>ab6cb534-8a29-41d6-9f7e-6d66375ec665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
