<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NegativeFileCheckCheckEligibility</name>
   <tag></tag>
   <elementGuidId>78c9a20e-348a-443f-aad7-9175d87b827d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table713_button444</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='table713_button444']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19526cd0-0be7-45d5-9584-fb29b609281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onClickNegativeCheck){onClickNegativeCheck(this,event);}</value>
      <webElementGuid>2d02fd78-c927-4570-900b-cb2deb785655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer  advancedListviewControl</value>
      <webElementGuid>5b6e6ee4-d106-494c-93fc-643efb7bb279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbf128e2-2dce-4e4e-a9ce-e44e5df4a8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table713_button444</value>
      <webElementGuid>9f2758df-5b42-4cec-a6d6-2aec470399eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table713_button444</value>
      <webElementGuid>3fa1d01c-6426-4f8a-9208-08bb37a26575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>53bfd66c-46d3-4854-87d3-158842bf71d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table713_button444&quot;)</value>
      <webElementGuid>2b3c8c6d-e9e8-482b-9921-49d0be7301dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>430b62c6-bece-4fc6-99be-72659f172e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='table713_button444']</value>
      <webElementGuid>eda10fde-2491-4e40-937d-7755d15ae883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table713_frame688']/div/div/div[8]/div/button</value>
      <webElementGuid>2e3b5bf1-75d6-4ddf-b52f-f54677d763bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[573]/following::button[1]</value>
      <webElementGuid>bb68afa5-c99e-43b7-b2e8-67a710237055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[287]/following::button[1]</value>
      <webElementGuid>507b43a7-0000-477c-ac28-4fe99945ea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[14]/preceding::button[1]</value>
      <webElementGuid>8f3912c4-b4d3-4734-9d1b-396f7adc5078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[574]/preceding::button[1]</value>
      <webElementGuid>e0870a98-519f-4091-ad83-0388cdf0883c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[8]/div/button</value>
      <webElementGuid>14b89a6d-eac1-43a2-a8d7-9876e15ad1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'table713_button444' and @id = 'table713_button444' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>b62059f8-8cda-4c62-a4e4-e08d7894d7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
