<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NTBOrETBCheckSaveChanges</name>
   <tag></tag>
   <elementGuidId>edb610af-cf50-41e3-829b-5ccab7cb1a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAdvancedListviewchanges_NTB_ETB_Check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveAdvancedListviewchanges_NTB_ETB_Check']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0056b24e-d140-4e2d-89fa-68de451126f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>a1f7b770-4e43-40d6-a802-f120ed493c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modifyAdvancedRowTableData('NTB_ETB_Check');</value>
      <webElementGuid>376a433f-5388-47d7-9e52-9d16b73b53b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAdvancedListviewchanges_NTB_ETB_Check</value>
      <webElementGuid>5b8f97b5-fb19-4ae2-b7f3-34499afa5749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbbee961-0510-40a2-b1e4-7085174ebeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>cdcba400-3c87-41cd-962c-a193a4f5bc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAdvancedListviewchanges_NTB_ETB_Check&quot;)</value>
      <webElementGuid>f60f6f08-dbb3-46b6-a8eb-bb0773c62893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>881ad284-bc6e-44b6-8752-0fea507a4dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveAdvancedListviewchanges_NTB_ETB_Check']</value>
      <webElementGuid>469a5855-3e86-43d4-b993-069dea90ce53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedListViewModalContent']/div/div/span[2]/div[2]/button</value>
      <webElementGuid>ff028ae0-e99a-4455-bba1-24d56d5cc23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NTB/ETB Check'])[2]/following::button[1]</value>
      <webElementGuid>d4f73180-3e82-457c-92c4-679e8d21ccce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[566]/following::button[3]</value>
      <webElementGuid>42777b6e-9e1e-4427-ab72-38d4a048da7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Name'])[14]/preceding::button[2]</value>
      <webElementGuid>1a311923-57f5-433b-ab45-c97701dd5ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[\s\S]*'])[294]/preceding::button[2]</value>
      <webElementGuid>b108402a-4dec-458c-95af-15083a4aa6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[2]/button</value>
      <webElementGuid>18b92257-2dd0-4f9e-bb5d-857afae71651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveAdvancedListviewchanges_NTB_ETB_Check' and @type = 'button' and (text() = 'Save Changes' or . = 'Save Changes')]</value>
      <webElementGuid>ffc89520-dbf2-4723-a39c-a191b253af44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
