<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NTBOrETBCheckCheckEligibility</name>
   <tag></tag>
   <elementGuidId>c635398b-7aca-43f2-9dbc-b8f589afcfb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table714_button445</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='table714_button445']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b1cd0d6-8308-411e-8fb8-1823518f25a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onClickETBNTBCheck){onClickETBNTBCheck(this,event);}</value>
      <webElementGuid>9e447eef-4fbd-4af9-9a2f-ef779303a12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer  advancedListviewControl</value>
      <webElementGuid>80280e9f-a71d-47ee-bfc3-c0ebfb9dba77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0c30926-4dd4-4e5d-a027-8cf80de0e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table714_button445</value>
      <webElementGuid>4336a51b-abb0-4e42-a408-763749d00b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table714_button445</value>
      <webElementGuid>f1d4f6d3-5f63-4657-8aa8-9f46acffbe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>a6b70f7f-1214-47cd-8912-1a65cf428910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table714_button445&quot;)</value>
      <webElementGuid>275ac41f-2e31-49ec-9539-efd78fc06935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>7c71fbe5-1aef-4fbe-acf3-edd6b054ff08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='table714_button445']</value>
      <webElementGuid>64643a41-7b0c-4737-b648-a2d2d043d33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table714_frame690']/div/div/div[5]/div/button</value>
      <webElementGuid>8d2dca02-f3b6-4c9e-8b81-774bf29015ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[570]/following::button[1]</value>
      <webElementGuid>ecf65124-ca5e-4487-bd54-f64fcec0c685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[286]/following::button[1]</value>
      <webElementGuid>95ece8d4-d14c-42f6-b1ab-3d9e44483803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[14]/preceding::button[1]</value>
      <webElementGuid>af1d6dc4-9f8b-4e96-9f15-4977a86b4332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[571]/preceding::button[1]</value>
      <webElementGuid>568a4337-db63-4202-97e2-16953a5cf900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>0d9843be-fb4c-4824-86a8-880d01c7c9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'table714_button445' and @id = 'table714_button445' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>6f634c7d-2f28-46c7-9ce6-c5e0b36bc9d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
