<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RPTCheckCheckEligibility</name>
   <tag></tag>
   <elementGuidId>59223c22-a7b7-4273-bc9c-030db8b3056b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table712_button443</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='table712_button443']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fb587f4-13ee-4a0a-bf26-23b8e18878b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(window.onClickRPTDOSRI){onClickRPTDOSRI(this,event);}</value>
      <webElementGuid>3d544ecd-dca0-49e2-8e77-5a29c4ccaf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle button-viewer  advancedListviewControl</value>
      <webElementGuid>fd710630-ca71-487e-b34c-ca33de9b0d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcf0ea3b-57bf-4694-b12d-e853af4c6663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table712_button443</value>
      <webElementGuid>35f9311f-cf3f-4ccd-93b0-f2cd4f8d4f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table712_button443</value>
      <webElementGuid>b5f4db70-10bb-45fc-9cf0-8b55442ae952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Check Eligibility</value>
      <webElementGuid>005ea6e1-c667-40a9-9268-c4c9ee83f20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table712_button443&quot;)</value>
      <webElementGuid>ad9dd2f6-3dbe-4ba1-b852-929f772dcc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>a16cec38-4748-45d0-8af9-bce800e91b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='table712_button443']</value>
      <webElementGuid>4d36abbb-5e9c-4cf2-9707-4203cde7f6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table712_frame687']/div/div/div[7]/div/button</value>
      <webElementGuid>f1e4b65d-3dd6-48a1-9821-48d104f99cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[563]/following::button[1]</value>
      <webElementGuid>a5d25406-a0ac-484b-80f9-0ef3b79c0c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANS'])[280]/following::button[1]</value>
      <webElementGuid>309e8471-103f-4816-b763-5b8e52a2d85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrower Type'])[13]/preceding::button[1]</value>
      <webElementGuid>91caadc4-5458-42eb-86ac-c18499260c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[564]/preceding::button[1]</value>
      <webElementGuid>0eb402b5-6e70-4322-85ed-5f7f3bc55ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>6e57f8d0-0906-4ffe-ade1-fe430c7197d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'table712_button443' and @id = 'table712_button443' and (text() = ' Check Eligibility' or . = ' Check Eligibility')]</value>
      <webElementGuid>50ffdf0a-da21-4cd2-b15c-528e9b2fa6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
