<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RPTCheckCoBorrower</name>
   <tag></tag>
   <elementGuidId>f5e9317d-d213-4dd3-8ed7-70f06e72a8ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table712']/tbody/tr[2]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d1bd518c-59ef-468f-adaa-9b4f783de920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelname</name>
      <type>Main</type>
      <value>Borrower Type</value>
      <webElementGuid>ff9de13f-4ef1-43cc-9537-283dd83b50ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class control-label fmarginbottom0 inputStyle listviewlabel </value>
      <webElementGuid>bd452c4b-ae82-4908-8036-e1390b6b567d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>390d0473-ccd6-41df-a02e-487853f8b1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PB</value>
      <webElementGuid>7ea159b3-e03b-483e-8f89-bb6e047c4d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>4ae95920-9891-4a6b-a324-9cf8bfc1ed16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table712&quot;)/tbody[1]/tr[1]/td[@class=&quot;fpadding3&quot;]/label[@class=&quot;control-class control-label fmarginbottom0 inputStyle listviewlabel&quot;]</value>
      <webElementGuid>69acd1ac-110b-4810-8de1-40f7357e0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>418481ac-4b5e-4a9d-8c8d-43d2c9642213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table712']/tbody/tr/td[2]/label</value>
      <webElementGuid>fd57411a-85b7-4fb9-a5bd-6d4ef3143234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[10]/following::label[2]</value>
      <webElementGuid>b11e5496-32cf-4773-8d42-a177fb8f5be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPT Status'])[1]/following::label[2]</value>
      <webElementGuid>eb9bdee2-9d10-4e93-aaa0-b7b7dd647da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a b c'])[2]/preceding::label[1]</value>
      <webElementGuid>9b70282e-984f-40fa-9b58-1015455d4381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOSRI Check'])[1]/preceding::label[6]</value>
      <webElementGuid>272c4717-0888-4f73-b16a-1c841436d45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[2]/label</value>
      <webElementGuid>0f3ff7b7-c257-48ad-acce-eb9ded642ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'PB' and (text() = 'Principal' or . = 'Principal')]</value>
      <webElementGuid>ca511cd0-fd8d-4d7c-a44c-dc4a76311c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
