<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RPTCheckPrincipal</name>
   <tag></tag>
   <elementGuidId>721f74b4-5674-41ea-b429-d78c0d97214a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table712']/tbody/tr[1]/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>395b886a-3f60-43c8-901f-e18bd645561d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelname</name>
      <type>Main</type>
      <value>Borrower Type</value>
      <webElementGuid>df68d90e-266a-42a7-a030-613fc23b5202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class control-label fmarginbottom0 inputStyle listviewlabel </value>
      <webElementGuid>d7d6878d-ac6c-401b-adf4-1b5428bbd07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>3a35fb93-6ccd-4fae-94b3-4b66a97df8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PB</value>
      <webElementGuid>bdbe6d79-b7ad-4137-8c51-c87c17514414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>623e98e4-9c8e-4e94-b42a-9c8bd9f274e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table712&quot;)/tbody[1]/tr[1]/td[@class=&quot;fpadding3&quot;]/label[@class=&quot;control-class control-label fmarginbottom0 inputStyle listviewlabel&quot;]</value>
      <webElementGuid>e419c1fa-8747-426c-86f8-bc87f73c9ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>b6a06763-3581-4035-9ef1-7feb18c38b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table712']/tbody/tr/td[2]/label</value>
      <webElementGuid>6002a9e4-ace7-4e24-9324-ba7e39f84e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[10]/following::label[2]</value>
      <webElementGuid>b9f78771-bf3c-4be8-908b-8c2731fb60d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPT Status'])[1]/following::label[2]</value>
      <webElementGuid>fc9b8536-1682-4185-b54d-d088cd9de9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a b c'])[2]/preceding::label[1]</value>
      <webElementGuid>7fac1c29-fb71-4eab-bb0c-d44f427d299b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOSRI Check'])[1]/preceding::label[6]</value>
      <webElementGuid>e3417eba-b009-431d-82f5-28645500a4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div[2]/div[2]/table/tbody/tr/td[2]/label</value>
      <webElementGuid>456b5765-ba9a-454e-821c-748913979577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'PB' and (text() = 'Principal' or . = 'Principal')]</value>
      <webElementGuid>3cd07f15-7d80-47cc-89a7-39d485add440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
