<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TransunionSaveChanges</name>
   <tag></tag>
   <elementGuidId>a217a090-c487-4bae-a273-e773e8811ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAdvancedListviewchanges_table715</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveAdvancedListviewchanges_table715']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f95a51a9-565e-409d-967b-0051c748aa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iform-button control-class buttonStyle</value>
      <webElementGuid>31a3f2f2-7f47-4052-ac61-b637af7ed028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modifyAdvancedRowTableData('table715');</value>
      <webElementGuid>902f2651-553e-4c11-a576-f2c57648320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAdvancedListviewchanges_table715</value>
      <webElementGuid>8312bf18-fdff-4da8-94c6-8928ab4a6bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c510475f-de6a-4ec2-bc0f-1d71346bbd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>5e860436-5f68-4c3c-9fea-78b740c38c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAdvancedListviewchanges_table715&quot;)</value>
      <webElementGuid>9e8bb1e3-d9a8-4cd1-bb96-ca76cf7b5137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>837c370f-cd80-4db0-b065-34664fe54da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveAdvancedListviewchanges_table715']</value>
      <webElementGuid>7a24a710-b2b8-411d-94d5-5bfd61021e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedListViewModalContent']/div/div/span[2]/div[2]/button</value>
      <webElementGuid>94e54e80-fe72-4846-b910-4cd1f2b9e856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transunion'])[2]/following::button[1]</value>
      <webElementGuid>b498f1e7-9a37-4d36-af7e-816b601bdfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing or Invalid Value'])[566]/following::button[3]</value>
      <webElementGuid>00801155-f97f-4b2d-89df-2a20c28e7a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transunion Result Section'])[1]/preceding::button[2]</value>
      <webElementGuid>3ee233db-e96e-438c-bb41-ebb1f89d78f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Name'])[14]/preceding::button[2]</value>
      <webElementGuid>c209a682-ca30-4c2d-978b-2bb90886149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[2]/button</value>
      <webElementGuid>d73ac6c4-0a53-4015-8320-0e6df109482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'saveAdvancedListviewchanges_table715' and @type = 'button' and (text() = 'Save Changes' or . = 'Save Changes')]</value>
      <webElementGuid>0ba9e0ca-9f50-4a4a-a5e9-dd1ba50603ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
