<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TransunionPrincipal</name>
   <tag></tag>
   <elementGuidId>25fc19ba-6401-4cf8-a7d1-9c782b8859b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table715']/tbody/tr/td[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d1d536f2-ba1d-484a-85ae-797e76858051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelname</name>
      <type>Main</type>
      <value>Borrower Type</value>
      <webElementGuid>24fd0ed4-da73-4133-9f4c-49b492e79fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-class control-label fmarginbottom0 inputStyle listviewlabel </value>
      <webElementGuid>4a4875b1-7d80-4e14-bb87-b2bc19c03681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maskingpattern</name>
      <type>Main</type>
      <value>nomasking</value>
      <webElementGuid>0e5659b1-6c6a-4cd1-bc4c-c0691ecb5e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PB</value>
      <webElementGuid>f8d5efb3-a297-4266-8738-e3513895f886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Principal</value>
      <webElementGuid>0abd97b2-1c70-4a52-929c-d010df71817c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table715&quot;)/tbody[1]/tr[1]/td[@class=&quot;fpadding3&quot;]/label[@class=&quot;control-class control-label fmarginbottom0 inputStyle listviewlabel&quot;]</value>
      <webElementGuid>a78ad7a4-0c40-4845-90c8-59d3d8f8087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BackOfficePaperBase/EncoderPaperbaseCheckEligibility/iframe_Form_ngformIframe</value>
      <webElementGuid>b575e124-52bf-441d-baa2-f528a9928882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table715']/tbody/tr/td[2]/label</value>
      <webElementGuid>ba480679-af86-47f7-9295-fa4a8423d8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddressMatch'])[1]/following::label[2]</value>
      <webElementGuid>ca883fdf-747e-4c43-abdc-023a72bb1870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[15]/following::label[2]</value>
      <webElementGuid>3cd24ba0-8f59-4ce8-ad58-b9ace2e990b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a b c'])[6]/preceding::label[1]</value>
      <webElementGuid>71b4737b-2acd-4490-9ce9-3bbd21589995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accuity'])[1]/preceding::label[8]</value>
      <webElementGuid>b045db91-46c4-4a89-a7e9-070bd3f9fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/table/tbody/tr/td[2]/label</value>
      <webElementGuid>fe12f9db-ce7c-4b2a-9ad4-0a6830130afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'PB' and (text() = 'Principal' or . = 'Principal')]</value>
      <webElementGuid>6cdf41f0-a8de-4864-baff-dbb627f87a38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
