<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_User Desktop</name>
   <tag></tag>
   <elementGuidId>553afdf0-2aba-479a-b355-717050a1548e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='form:dataTable:1:userViewName1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3fa47abc-6136-4f16-82d1-fa978e46112f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:dataTable:1:userViewName1</value>
      <webElementGuid>22a9b9d1-9376-4579-b867-6874f2bf7ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oacursorpointer</value>
      <webElementGuid>fcfc6477-2031-49b5-85e9-89b64445d4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
User Desktop</value>
      <webElementGuid>fccea13a-fc46-436d-abdf-dce8c9839d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:dataTable:1:userViewName1&quot;)</value>
      <webElementGuid>ee9bf90e-2069-409b-95d2-3641910c748e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='form:dataTable:1:userViewName1']</value>
      <webElementGuid>46426272-d4a3-4e2d-ac21-e0a288bb0470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form:dataTable']/tbody/tr[2]/td/div/label</value>
      <webElementGuid>14734233-fa23-4a36-bc6a-d3f9cca54b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit officers'])[1]/following::label[1]</value>
      <webElementGuid>4e79ba46-d48c-441b-99cf-8055a10d75f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Views'])[1]/following::label[2]</value>
      <webElementGuid>32395096-975f-4d74-aeb2-52f5df9d4a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User WorkSpace'])[1]/preceding::label[1]</value>
      <webElementGuid>e6acb95b-c856-4b66-8312-55b584efffc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save Layout'])[1]/preceding::label[2]</value>
      <webElementGuid>94b03167-fa00-4910-82d7-4b3d5e91b37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Desktop']/parent::*</value>
      <webElementGuid>92c6f42d-d5c3-4717-973e-ec6dd0d6972a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/label</value>
      <webElementGuid>8b1f6c65-d190-4a6d-8d30-a24db9ea0687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'form:dataTable:1:userViewName1' and (text() = '
User Desktop' or . = '
User Desktop')]</value>
      <webElementGuid>5bdde950-ec9f-496c-bdac-de060263812a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
